# 0A · Python, notebooks et outils — solutions (notebook exécuté)

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/cemah2/workbookIA/blob/main/chapitres/ch00a_python/05_solutions.ipynb)

Les solutions des exercices du notebook, exécutées. Les explications détaillées (le *pourquoi*, les erreurs fréquentes, les variantes) sont dans `05_solutions.md`. Les cellules marquées `answer` enregistrent les réponses vérifiées par `wb.check` (`tools/build_answers.py`).

| Partie | ID | Titre | Type | ★ | ⏱️ |
|---|---|---|---|---|---|
| 0 | 0A.1 à 0A.8 | vérifier tes exercices papier | ✏️ | ★ à ★★ | |
| A | 0A.13 | Ordre d'exécution des cellules : que vaut `x` ? | 🔮 | ★ | 10 |
| B | 0A.14 | Nombres et f-strings : la fiche d'un manchot | 🔨 | ★ | 13 |
|  | 0A.15 | Chaînes : nettoyer les noms d'espèces de Penguins brut | 🔨 | ★ | 13 |
|  | 0A.16 | Listes : les nageoires de dix manchots | 🔨 | ★ | 13 |
|  | 0A.17 | Tuples et déballage : renvoyer et échanger plusieurs valeurs | 🔨 | ★ | 13 |
|  | 0A.18 | Dictionnaires : une fiche par espèce | 🔨 | ★ | 15 |
|  | 0A.19 | Ensembles : quelles espèces sur quelles îles ? | 🔨 | ★ | 13 |
|  | 0A.20 | Conditions : classer un manchot selon sa masse | 🔨 | ★ | 13 |
|  | 0A.21 | Boucles : `for`, `range`, `enumerate`, `zip` et `while` | 🔨 | ★ | 15 |
|  | 0A.22 | Compréhensions : filtrer et transformer en une ligne | 🔨 | ★ | 15 |
| C | 0A.23 | Tes premières fonctions : paramètres, valeurs par défaut, `return` | 🔨 | ★ | 15 |
|  | 0A.24 | Importer des modules : `math`, `random`, `statistics` et `Counter` | 🔨 | ★ | 13 |
|  | 0A.25 | Exceptions : lever une `ValueError` et la rattraper | 🔨 | ★ | 15 |
|  | 0A.26 | Ton premier module mylearn : `mean` et son test | 🔨 | ★ | 15 |
| D | 0A.27 | Premiers arrays NumPy : `dtype`, `shape`, `ndim` | 📦 | ★ | 13 |
|  | 0A.28 | Indexation, tranches et masques booléens | 📦 | ★ | 15 |
|  | 0A.29 | Vue ou copie : qui est modifié ? | 🔮 | ★ | 10 |
|  | 0A.30 | Calcul vectorisé : unités, normalisation, fonctions universelles | 📦 | ★ | 15 |
|  | 0A.31 | Aléatoire reproductible : `default_rng`, graine, `permutation`, `choice` | 📦 | ★ | 15 |
| E | 0A.32 | Premier contact avec Penguins : `read_csv`, `head`, `info`, `describe` | 📦 | ★ | 13 |
|  | 0A.33 | Sélectionner : colonnes, `loc`, `iloc` et filtres | 📦 | ★ | 15 |
|  | 0A.34 | Valeurs manquantes et doublons : `isna`, `dropna`, `fillna`, `duplicated` | 📦 | ★ | 15 |
|  | 0A.35 | De pandas à NumPy : construire `X` et `y` | 📦 | ★ | 13 |
|  | 0A.36 | Premiers graphiques : `plot`, `scatter`, `hist` | 📦 | ★ | 15 |
| F, G, H | 0A.37 à 0A.67 | Python avancé, NumPy/pandas avancés, outils et mylearn | | | *prochaine session* |

In [1]:
# ⚙️ SETUP: run this cell first (on Colab or on your computer)
FAST_MODE = True  # True = quick version (CPU, a few minutes); False = full version
SEED = 42

import os
import subprocess
import sys
from pathlib import Path

REPO_URL = "https://github.com/cemah2/workbookIA.git"
DRIVE_DIR = Path("/content/drive/MyDrive/workbookIA")

try:
    import google.colab  # noqa: F401  (this module only exists on Colab)
    IN_COLAB = True
except ImportError:
    IN_COLAB = False

if IN_COLAB:
    from google.colab import drive

    drive.mount("/content/drive")
    subprocess.run(["git", "config", "--global", "--add", "safe.directory", str(DRIVE_DIR)])
    if not (DRIVE_DIR / ".git").exists():
        subprocess.run(["git", "clone", REPO_URL, str(DRIVE_DIR)], check=True)
    else:
        # Get the new chapters. Your own work only lives in mon_travail/, which Claude never
        # touches, so "rebase + autostash" keeps it safe (even with local commits).
        identity = subprocess.run(["git", "-C", str(DRIVE_DIR), "config", "user.email"],
                                  capture_output=True).returncode == 0
        who = [] if identity else ["-c", "user.name=Workbook", "-c", "user.email=workbook@localhost"]
        pull = subprocess.run(["git", *who, "-C", str(DRIVE_DIR), "pull", "--rebase", "--autostash"],
                              capture_output=True, text=True)
        if pull.returncode != 0:
            print("⚠️ git pull a échoué (voir 00_setup/COLAB.md, « Problèmes fréquents ») :\n" + pull.stderr)
    ROOT = DRIVE_DIR
else:
    ROOT = Path(os.environ.get("WB_ROOT", Path.cwd())).resolve()
    while not (ROOT / "src" / "wb").exists() and ROOT != ROOT.parent:
        ROOT = ROOT.parent
    if not (ROOT / "src" / "wb").exists():
        raise FileNotFoundError("Dépôt introuvable : ouvre ce notebook depuis le dossier du workbook.")

os.environ["WB_ROOT"] = str(ROOT)
if str(ROOT / "src") not in sys.path:
    sys.path.insert(0, str(ROOT / "src"))

import wb  # noqa: E402

cfg = wb.setup(seed=SEED, fast=FAST_MODE)
FAST_MODE = cfg.fast
mylearn = wb.load_mylearn("ref")  # reference implementation

🧪 Deep Learning Workbook : environnement
   Plateforme : Local (Linux x86_64, 2 CPU)
   Python 3.13.13 | numpy 2.1.3 | pandas 2.2.3 | matplotlib 3.10.0 | scikit-learn 1.6.1 | scipy 1.16.3 | torch 2.11.0+cpu | torchvision 0.26.0+cpu
   Device : cpu | Graine : 42 | FAST_MODE : True

## Objectifs et rappel express

- Utiliser un notebook sans se perdre : ordre d'exécution, « Run all », `wb.check`.
- Écrire du Python lisible : types, listes, dictionnaires, ensembles, boucles, compréhensions, fonctions, exceptions.
- Faire ses premiers pas avec NumPy (arrays, masques, vectorisation, aléatoire) et pandas (lire, sélectionner, valeurs manquantes, `X` et `y`).
- Écrire et tester ta première fonction de mylearn.

**Rappel express.** L'état du notebook dépend de l'ordre d'exécution ; les indices commencent à 0 et la fin d'une tranche est exclue ; une fonction **renvoie** avec `return` ; un array NumPy n'a qu'un type et se calcule sans boucle ; `axis=0` donne une valeur par colonne.

## Partie 0 · Vérifier tes exercices papier (0A.1 à 0A.8)

Fais d'abord les exercices ✏️ de `02_exercices.md` **sur papier**, dans ta copie de `06_mes_reponses.md`. Reporte ensuite chaque réponse ici : **la valeur** que tu as trouvée (`3`, `"float"`, `[1, 2]`, `(4, 6)`…), pas l'expression Python, sinon tu ne vérifies rien. Les réponses pas encore remplies affichent ⏳.

In [2]:
# Data of the paper exercises (the same as in 02_exercices.md)
import math

import numpy as np
import pandas as pd

masses = [3750, 3800, 3250, 3450, 3650, 3625]          # 0A.2
name = "Chinstrap"
point = (39.1, 18.7, 181)

values = [4, 7, 1, 8, 3, 6]                              # 0A.3
total = 0
count = 0
for i, v in enumerate(values):
    if v % 2 == 0:
        total += v * i
    elif v > 5:
        count += 1
n = 100
steps = 0
while n > 1:
    n = n // 3
    steps += 1

df = pd.DataFrame({                                      # 0A.4
    "species": ["Adelie", "Adelie", "Gentoo", "Chinstrap", "Gentoo", "Adelie", "Chinstrap", "Gentoo"],
    "island": ["Torgersen", "Dream", "Biscoe", "Dream", "Biscoe", "Biscoe", "Dream", "Biscoe"],
    "body_mass_g": [3750, 3400, 5200, 3700, 4650, 3900, 3950, 5550],
    "sex": ["male", "female", "male", "female", "female", "male", "male", "male"],
})

rate = 10                                                # 0A.6


def price(quantity, unit=2, *, discount=0):
    rate = 5
    return quantity * unit * rate - discount


a = price(3)
b = price(3, 4)
c = price(2, discount=7)
d = price(unit=1, quantity=4)
e = rate
try:
    price(1, 2, 3)
    error_name = "no error"
except Exception as error:  # noqa: BLE001 - we want the name of whatever is raised
    error_name = type(error).__name__

A = np.arange(24).reshape(4, 6)                          # 0A.7
B = np.zeros((3, 28, 28))


def broadcast(shape_a, shape_b):                         # 0A.8
    """Shape of the result as a string, or "erreur"."""
    try:
        return str(np.broadcast_shapes(shape_a, shape_b))
    except ValueError:
        return "erreur"

**Ex 0A.1 — Évaluer des expressions à la main : //, %, **, conversions**

In [3]:
wb.record("0A.1a", 17 // 5)
wb.record("0A.1b", 17 % 5)
wb.record("0A.1c", -17 // 5, mistakes={"// arrondit vers le bas (vers moins l'infini), pas vers zéro": -3})
wb.record("0A.1d", (2 + 3) ** 2 - 10 // 3, mistakes={"les parenthèses passent en premier : (2 + 3) ** 2 vaut 25": 8})
wb.record("0A.1e", int(7.9) + round(7.5), mistakes={"int(7.9) tronque : il vaut 7, pas 8": 16, "round(7.5) vaut 8 : au milieu, Python arrondit au nombre pair le plus proche": 14})
wb.record("0A.1f", 10 / 4 * 2, decimals=1, mistakes={"/ et * ont la même priorité : on calcule de gauche à droite, (10 / 4) * 2": 1.25})
wb.record("0A.1g", type(7 / 7).__name__, mistakes={"/ donne toujours un float, même quand la division tombe juste": "int"})

WB_ANSWER {"hash": "0f26990d99c8ad09dde09b5717fd37ba4bf94e27e6ff73022b99fa362a4c9231", "id": "0A.1a", "kind": "int", "magnitude": 0, "sign": 1}
📝 Ex 0A.1a : réponse enregistrée (int).
WB_ANSWER {"hash": "1ab55ffa3bdbf6141347277124b3716015f49c1e79b64799e707d9afd9556d74", "id": "0A.1b", "kind": "int", "magnitude": 0, "sign": 1}
📝 Ex 0A.1b : réponse enregistrée (int).
WB_ANSWER {"hash": "e08e18872f01b5ac8c0d3aa31f6f247f824a0473df7115c1eae310bf90a6ab6b", "id": "0A.1c", "kind": "int", "magnitude": 0, "mistakes": {"802a5539a9ac8e4d8cba06706f7124f61c29be9c086c16e8415f98a2823d2d8f": "// arrondit vers le bas (vers moins l'infini), pas vers zéro"}, "sign": -1}
📝 Ex 0A.1c : réponse enregistrée (int).
WB_ANSWER {"hash": "2b99c509722d83529658512d09145a8f9759f66cc1a1e2f748486897386ecbb6", "id": "0A.1d", "kind": "int", "magnitude": 1, "mistakes": {"6996baf8b2aab74f6fed0e5caef073893a7d5f3fa3561355b63e2713945fbcdd": "les parenthèses passent en premier : (2 + 3) ** 2 vaut 25"}, "sign": 1}
📝 Ex 0A.1d : réponse enregistrée (int).
WB_ANSWER {"hash": "8ec4d10febae1181ec64fdf33f3dcf2172dd24ef39373e78cecef8554893d765", "id": "0A.1e", "kind": "int", "magnitude": 1, "mistakes": {"569a0b89fde4f43f14e968e1c593dfca6a448d57b66b585ce3977ad84d9b06f1": "int(7.9) tronque : il vaut 7, pas 8", "b2f0c3e7a91f7833c4f4165bbae32d6c3dcbedeb94d18f7675e26ba8c51864c8": "round(7.5) vaut 8 : au milieu, Python arrondit au nombre pair le plus proche"}, "sign": 1}
📝 Ex 0A.1e : réponse enregistrée (int).
WB_ANSWER {"decimals": 1, "hash": "a4cea80465ed4a52ab324ded9eea62d1f13a08c7f9967a66070e065e5e51cf3e", "hash_coarse": "8fa26832edbd4f1fa1358afb0aa40af7a506a5c49b4c022a971c9014ce2cbce1", "id": "0A.1f", "kind": "float", "magnitude": 0, "mistakes": {"20bd8761fb74381af6d0c300dbf14804b7867c16b975bcc929b5d34d76f3e2d6": "/ et * ont la même priorité : on calcule de gauche à droite, (10 / 4) * 2"}, "sign": 1}
📝 Ex 0A.1f : réponse enregistrée (float, 1 décimale(s)).
WB_ANSWER {"hash": "7fdf3322b4e36fd7a891604049bcc6635b7f78e764a1a9cec43ff32d50df539a", "id": "0A.1g", "kind": "str", "mistakes": {"890ae8ddbe53943401798aa5eb2cdfa094500f4fc04543c83d7af4fac9dbd9a1": "/ donne toujours un float, même quand la division tombe juste"}}
📝 Ex 0A.1g : réponse enregistrée (str).

**Ex 0A.2 — Indices et tranches à la main**

In [4]:
wb.record("0A.2a", masses[2])
wb.record("0A.2b", masses[-2], mistakes={"-1 est le dernier élément, -2 l'avant-dernier": masses[-3]})
wb.record("0A.2c", masses[1:4], mistakes={"la fin d'une tranche est exclue": masses[1:5]})
wb.record("0A.2d", masses[::2])
wb.record("0A.2e", name[:5])
wb.record("0A.2f", name[-4:])
wb.record("0A.2g", len(masses[2:]))
wb.record("0A.2h", point[2] - point[0], decimals=1)

WB_ANSWER {"hash": "f5d3afb2f66459178ac8ec724856c3aaf04be20d2e0000c0557f3cfde18c9e44", "id": "0A.2a", "kind": "int", "magnitude": 3, "sign": 1}
📝 Ex 0A.2a : réponse enregistrée (int).
WB_ANSWER {"hash": "e6542f74fe2cb7f3ef617bdbde0ed14d472f2dafeea78d4485dc2028a553c644", "id": "0A.2b", "kind": "int", "magnitude": 3, "mistakes": {"7310f2e3cdddd10484c36ef7a90503e1677604f698ed7d6df7c06ab6ef096961": "-1 est le dernier élément, -2 l'avant-dernier"}, "sign": 1}
📝 Ex 0A.2b : réponse enregistrée (int).
WB_ANSWER {"decimals": 0, "element_hashes": ["fa775f56dfa26fec2e223513d157a10af5c438125f5ec1095ba3c52a7837d9f6", "d8a807b7985fb5dfe2a37bb0535d86e67cb0cfa22dfb1eb89329b4d046909367", "c6377de9cd3dfc7ff8b2f0c54a473e84289bbaa74a692030c591028fb9d027fa"], "hash": "0a89de2b0a9dccf0726f3456076ac0cbfbfdf7b729b6eaf26ca2e6f5c10a8e13", "id": "0A.2c", "integer": true, "kind": "array", "mistakes": {"31b517e0b6d213f786a75c2fdf6513a2446828c35d8f664fff8066ee576991a5": "la fin d'une tranche est exclue"}, "shape": [3]}
📝 Ex 0A.2c : réponse enregistrée (array, 0 décimale(s)).
WB_ANSWER {"decimals": 0, "element_hashes": ["35dc6342d30e58f8742483178ab404e0032141edc41722f7a66f86bb93de792c", "7c25a5c420fb139274bf0bb22e08c25135c35796c2fbab23880061178a0c52eb", "159f76f5541992e637d788de7b55328d79802b8a53ecc76f6bc8bedf419e4033"], "hash": "cd260a57be8855b91fbedbdb21aaae400551f4e14101092dfb20b79b34159924", "id": "0A.2d", "integer": true, "kind": "array", "shape": [3]}
📝 Ex 0A.2d : réponse enregistrée (array, 0 décimale(s)).
WB_ANSWER {"hash": "18d6f7acfa564838f7ead3fe0df442df4964ec6a32def2bfa5d547ad77343cdd", "id": "0A.2e", "kind": "str"}
📝 Ex 0A.2e : réponse enregistrée (str).
WB_ANSWER {"hash": "ad58b725ea5dfa38c62cb669f7033f8024648c29c4046a98fe88f936ebcd1689", "id": "0A.2f", "kind": "str"}
📝 Ex 0A.2f : réponse enregistrée (str).
WB_ANSWER {"hash": "fb22bba92fbd343b3f1abf60127670abb0e467c7f1e51c8617a32911e0eadf3e", "id": "0A.2g", "kind": "int", "magnitude": 0, "sign": 1}
📝 Ex 0A.2g : réponse enregistrée (int).
WB_ANSWER {"decimals": 1, "hash": "1dcbf23b76d0abe77b820803e3f89cc4f4bf560521034a147f8c0d2295946558", "hash_coarse": "41b17b2f2cc4cf49e4d9e2b5ae1bdd96b60947fedfd824d937f1b944ed4c6bcb", "id": "0A.2h", "kind": "float", "magnitude": 2, "sign": 1}
📝 Ex 0A.2h : réponse enregistrée (float, 1 décimale(s)).

**Ex 0A.3 — Dérouler une boucle et une compréhension**

In [5]:
wb.record("0A.3a", total)
wb.record("0A.3b", count)
wb.record("0A.3c", [v * 2 for v in values if v > 4])
wb.record("0A.3d", sum(v for v in values if v % 3 == 0))
wb.record("0A.3e", steps)

WB_ANSWER {"hash": "a6bcf0048257dad0a1ebec224fcf5b4e6d9a9cfda44077e5311a73b94731f826", "id": "0A.3a", "kind": "int", "magnitude": 1, "sign": 1}
📝 Ex 0A.3a : réponse enregistrée (int).
WB_ANSWER {"hash": "67fa6eaa00c7bb867f8cd3e7058bde604182f25b8b5c461ad52a029a028d1912", "id": "0A.3b", "kind": "int", "magnitude": 0, "sign": 1}
📝 Ex 0A.3b : réponse enregistrée (int).
WB_ANSWER {"decimals": 0, "element_hashes": ["eaf440b05b98858c2e64ae586bb6177999cbb927bdd7d09af1fe244de0217277", "5551c7c3a9c2e3ed148182f3d0f0119f1bbdd61b186006094380d4b08f9f8daf", "b81861bd760ef1f2a9c4a556f2f9bb3742d191931dc8de73dc0447315c149a49"], "hash": "5048b5042eeab1abb0a781f045272f51ebd429aab210d5b477e524e069def5a4", "id": "0A.3c", "integer": true, "kind": "array", "shape": [3]}
📝 Ex 0A.3c : réponse enregistrée (array, 0 décimale(s)).
WB_ANSWER {"hash": "055440f41668db93638f1599f002609c7cab25db308497f76d7c9c0ea46e77e0", "id": "0A.3d", "kind": "int", "magnitude": 0, "sign": 1}
📝 Ex 0A.3d : réponse enregistrée (int).
WB_ANSWER {"hash": "4ebbba1ab4014d362dbb591655e422d61b6cad8c6382647dc350fb48f3499ea0", "id": "0A.3e", "kind": "int", "magnitude": 0, "sign": 1}
📝 Ex 0A.3e : réponse enregistrée (int).

**Ex 0A.4 — Un groupby à la main sur huit manchots**

In [6]:
wb.record("0A.4a", df.groupby("species")["body_mass_g"].mean()["Gentoo"], decimals=1)
wb.record("0A.4b", df.groupby("species")["body_mass_g"].mean()["Adelie"], decimals=1)
wb.record("0A.4c", (df["island"] == "Dream").sum())
wb.record("0A.4d", df.groupby("island")["body_mass_g"].max()["Dream"])
wb.record("0A.4e", df[df["sex"] == "male"]["species"].value_counts()["Gentoo"])
wb.record("0A.4f", df.groupby("species")["body_mass_g"].mean().idxmin())

WB_ANSWER {"decimals": 1, "hash": "279916169641fe30ec68baee25bc15e291cb6c7f00e8114e7cadbbbc4cec99f8", "hash_coarse": "f93c119514d7b93f56a1b328810aafc0ae24169e790b3be79c87886de524f6f0", "id": "0A.4a", "kind": "float", "magnitude": 3, "sign": 1}
📝 Ex 0A.4a : réponse enregistrée (float, 1 décimale(s)).
WB_ANSWER {"decimals": 1, "hash": "7e9cd25f22c24a8ab8bc0f4b10463032a08e400994541011e03c0d7d3e614c64", "hash_coarse": "485b52698fee6feed11246bab3127ca8a7257b38185bb563cb32a83ef751e1ec", "id": "0A.4b", "kind": "float", "magnitude": 3, "sign": 1}
📝 Ex 0A.4b : réponse enregistrée (float, 1 décimale(s)).
WB_ANSWER {"hash": "f0f23163646d122b20f043abcce889140754b75dfc3724904ad31ca76a876a9b", "id": "0A.4c", "kind": "int", "magnitude": 0, "sign": 1}
📝 Ex 0A.4c : réponse enregistrée (int).
WB_ANSWER {"hash": "f3533e437057b6d1c91577a0217572451d65f00d3ca14de84237635de2670c86", "id": "0A.4d", "kind": "int", "magnitude": 3, "sign": 1}
📝 Ex 0A.4d : réponse enregistrée (int).
WB_ANSWER {"hash": "ee553618eacb9f696f53b415b0b005f5d28a38999367db0d9133f34318916219", "id": "0A.4e", "kind": "int", "magnitude": 0, "sign": 1}
📝 Ex 0A.4e : réponse enregistrée (int).
WB_ANSWER {"hash": "f4d449637e0f62d213e551e57a81d5ed4edbbab0d143785194472241b676a7b9", "id": "0A.4f", "kind": "str"}
📝 Ex 0A.4f : réponse enregistrée (str).

**Ex 0A.5 — Mini-lots : combien de lots, de quelle taille, combien de mises à jour ?**

In [7]:
wb.record("0A.5a", math.ceil(333 / 64), mistakes={"le dernier lot, incomplet, compte aussi : arrondis vers le haut": 5})
wb.record("0A.5b", 333 - 64 * (333 // 64), mistakes={"c'est le reste de la division de 333 par 64": 5})
wb.record("0A.5c", 333 // 64)
wb.record("0A.5d", 20 * math.ceil(333 / 64), mistakes={"avec drop_last=True, ce serait 100 : ici le dernier lot est gardé": 100})
wb.record("0A.5e", 333)
wb.record("0A.5f", 20)

WB_ANSWER {"hash": "dd3cc24a58739c1610c342f8f1472b4f20a3ec159caee6d19ba22b8251a56468", "id": "0A.5a", "kind": "int", "magnitude": 0, "mistakes": {"bdb9d859f5d0da9269777c676865716ad1a13026d8c1df11532b07b95e3dc2a6": "le dernier lot, incomplet, compte aussi : arrondis vers le haut"}, "sign": 1}
📝 Ex 0A.5a : réponse enregistrée (int).
WB_ANSWER {"hash": "0b5d70c0806ad6435f420a23744ff60117f47489fd0dca63358b2aa9b1904305", "id": "0A.5b", "kind": "int", "magnitude": 1, "mistakes": {"015f724b386696b691cd36dcf06d6770bab88d4b055c2f122f037f99d993b9a7": "c'est le reste de la division de 333 par 64"}, "sign": 1}
📝 Ex 0A.5b : réponse enregistrée (int).
WB_ANSWER {"hash": "f26d41fb96c8efa13a263c0021f69f66022988ad8e84d0b3336ec0284ae3944d", "id": "0A.5c", "kind": "int", "magnitude": 0, "sign": 1}
📝 Ex 0A.5c : réponse enregistrée (int).
WB_ANSWER {"hash": "d738ba311032392a0db2d36c21116b77cb9a926fbbc3168155b1429b5568fa64", "id": "0A.5d", "kind": "int", "magnitude": 2, "mistakes": {"0d0ec6ac19fade8b7b8b818729eeadb484b6b0846b73da4b17ecf0f821a0abae": "avec drop_last=True, ce serait 100 : ici le dernier lot est gardé"}, "sign": 1}
📝 Ex 0A.5d : réponse enregistrée (int).
WB_ANSWER {"hash": "d2b01067b20c7cfdce6b80585fcd09afc31322cbef514def437a9b76e3ad656a", "id": "0A.5e", "kind": "int", "magnitude": 2, "sign": 1}
📝 Ex 0A.5e : réponse enregistrée (int).
WB_ANSWER {"hash": "45648bab1a8be05c5bed6ffba3c238cc393dee50fc63ead75d9818b298fac250", "id": "0A.5f", "kind": "int", "magnitude": 1, "sign": 1}
📝 Ex 0A.5f : réponse enregistrée (int).

**Ex 0A.6 — Portée, valeurs par défaut et arguments nommés**

In [8]:
wb.record("0A.6a", a, mistakes={"dans price, rate est une variable locale qui vaut 5": 60})
wb.record("0A.6b", b, mistakes={"dans price, rate est une variable locale qui vaut 5": 120})
wb.record("0A.6c", c)
wb.record("0A.6d", d)
wb.record("0A.6e", e, mistakes={"rate = 5 est locale à la fonction : la variable globale rate n'a pas changé": 5})
wb.record("0A.6f", error_name)

WB_ANSWER {"hash": "845387a1084878d6f677195181d35a1bae8674220e25740b15d7844a9ca37ca7", "id": "0A.6a", "kind": "int", "magnitude": 1, "mistakes": {"26de8132a6d14761981c3818f2ff7f4d05bcfb1dcbd264c1bc3d5ea4e23cee51": "dans price, rate est une variable locale qui vaut 5"}, "sign": 1}
📝 Ex 0A.6a : réponse enregistrée (int).
WB_ANSWER {"hash": "46cc82d83e4eb5529fe23da8581cee69ac3dcdd8c31064201b08f4c12bc1eecf", "id": "0A.6b", "kind": "int", "magnitude": 1, "mistakes": {"c12fcf1212efcf37d97da2184d4b26b32dcbd793072cec31fc45cf52c1930ff2": "dans price, rate est une variable locale qui vaut 5"}, "sign": 1}
📝 Ex 0A.6b : réponse enregistrée (int).
WB_ANSWER {"hash": "103f5b50277c83b3f80a739244162984b92d9598e588d42c19ce7d8ae5ddd2c6", "id": "0A.6c", "kind": "int", "magnitude": 1, "sign": 1}
📝 Ex 0A.6c : réponse enregistrée (int).
WB_ANSWER {"hash": "dd2101214797aea87287f6a22db4fbff3a895886272eea60b6dc29151fbc2516", "id": "0A.6d", "kind": "int", "magnitude": 1, "sign": 1}
📝 Ex 0A.6d : réponse enregistrée (int).
WB_ANSWER {"hash": "fe44a052087f99f0afe4476f1d907a59937df21f2f52a4dabfe7e09d0906a916", "id": "0A.6e", "kind": "int", "magnitude": 1, "mistakes": {"694ea349f3fbc8a360114159389245462981b12cb2ef15092385a1d15691c5c6": "rate = 5 est locale à la fonction : la variable globale rate n'a pas changé"}, "sign": 1}
📝 Ex 0A.6e : réponse enregistrée (int).
WB_ANSWER {"hash": "44eb88633d8244b040d411cc7c5d39c27cbd4700b4c51e2dcfb00cc5d425f545", "id": "0A.6f", "kind": "str"}
📝 Ex 0A.6f : réponse enregistrée (str).

**Ex 0A.7 — Formes NumPy à la main**

In [9]:
wb.record("0A.7a", A[1:3].shape)
wb.record("0A.7b", A[:, 2].shape, mistakes={"un seul indice (2) retire l'axe ; une tranche (2:3) le garderait": (4, 1)})
wb.record("0A.7c", A[:, 2:3].shape, mistakes={"une tranche garde l'axe, même si elle ne contient qu'une colonne": (4,)})
wb.record("0A.7d", A.sum(axis=0).shape, mistakes={"axis=0 fait disparaître l'axe des lignes : il reste une valeur par colonne": (4,)})
wb.record("0A.7e", A.mean(axis=1, keepdims=True).shape)
wb.record("0A.7f", A.reshape(2, -1, 3).shape)
wb.record("0A.7g", B.reshape(len(B), -1).shape)
wb.record("0A.7h", A[A > 20].shape, mistakes={"un masque booléen renvoie un tableau à UNE dimension des éléments retenus": (4, 6)})
wb.record("0A.7i", A[2, 3])

WB_ANSWER {"decimals": 0, "element_hashes": ["b622848c0fd3b8bb53020ef0fa46c613760c9b39fb8626c75851c30d3c91aa3a", "2ee54d5787a6ac5f6f9d494e33e6c191f647a30e0e13b118666cd3dbfc1d20a7"], "hash": "ad7bc5aad1e14b321cdf447519a44c2dc03181d80df7e49069acc8381d2126e2", "id": "0A.7a", "integer": true, "kind": "array", "shape": [2]}
📝 Ex 0A.7a : réponse enregistrée (array, 0 décimale(s)).
WB_ANSWER {"decimals": 0, "hash": "bc1f2c4041362919609011fe5932b69ca870ed68652e54dfcff4b7ed003e2f3d", "id": "0A.7b", "integer": true, "kind": "array", "mistakes": {"6763aa921b34215fc3146515a235dc5210331bd2b1cfaffb7ec7ac5794560d40": "un seul indice (2) retire l'axe ; une tranche (2:3) le garderait"}, "shape": [1]}
📝 Ex 0A.7b : réponse enregistrée (array, 0 décimale(s)).
WB_ANSWER {"decimals": 0, "element_hashes": ["e88d2e4d12135d1b3f8464371c13981f9d6e1c6565e0bb4866fcaed0d9ac4ea1", "31b0bca6abb404312e50df46a0f142ced53e799466143833e427fc4e0e02d7cb"], "hash": "2dd7a4f7df30495a7b7f8a60e5bf0c2b499f80af9a6d42843e35787bde89ebe8", "id": "0A.7c", "integer": true, "kind": "array", "mistakes": {"a6727964e1ed06b1a76c55af624d311171432faadb1b0663a3f51bc69c221527": "une tranche garde l'axe, même si elle ne contient qu'une colonne"}, "shape": [2]}
📝 Ex 0A.7c : réponse enregistrée (array, 0 décimale(s)).
WB_ANSWER {"decimals": 0, "hash": "a0aeb026b8918fc54e170cf69a7e0d8c232cdca7bd359389f519e3f98eff13e5", "id": "0A.7d", "integer": true, "kind": "array", "mistakes": {"fd1c9bad6d6ddbab958e965a4b8ee8c9020d56e9c70def787fe69e86d90c8fdb": "axis=0 fait disparaître l'axe des lignes : il reste une valeur par colonne"}, "shape": [1]}
📝 Ex 0A.7d : réponse enregistrée (array, 0 décimale(s)).
WB_ANSWER {"decimals": 0, "element_hashes": ["d97793a9d8b5a0a668aaed803e52e680868658daaa0a2622854a564272d78b28", "263f20a0191b6e7a04e0d4bf3451f40e0ae6765d1e30a8b13af017b3c47fa723"], "hash": "0f2c7f0ea0499c1a56ddbd5c72e4ad209d56f09970c3db9bd6b7c1e05f80d5f9", "id": "0A.7e", "integer": true, "kind": "array", "shape": [2]}
📝 Ex 0A.7e : réponse enregistrée (array, 0 décimale(s)).
WB_ANSWER {"decimals": 0, "element_hashes": ["8c8bc1e7baff108574d13c21644531d11284760c7e7c721018d9281096392c75", "53e4da17824675d9a8cbced09a87078e759c10f503376d8ce7e0caa56e0a902d", "b2da2545f7bd2614f431cb3fa2dbce402e90522ca045a33c0a062b4a2ecf7747"], "hash": "009407df82085a70d592c51e9ca4e23a65517d60847dc5b33dd61f6898d88a72", "id": "0A.7f", "integer": true, "kind": "array", "shape": [3]}
📝 Ex 0A.7f : réponse enregistrée (array, 0 décimale(s)).
WB_ANSWER {"decimals": 0, "element_hashes": ["8f91e23a142d2ba113fc4a7f4561176ab96c2d8a76157da21b8a605acc83719a", "504e9ed9453e1f564eedb1e08d6e3fdf9cc1944f9286d699526404b5c41ffa37"], "hash": "cd2ed72755645d95f46254412d5e3ad25d222cd6cda2f5c1f0f9df1bb98c2687", "id": "0A.7g", "integer": true, "kind": "array", "shape": [2]}
📝 Ex 0A.7g : réponse enregistrée (array, 0 décimale(s)).
WB_ANSWER {"decimals": 0, "hash": "0897299db0fd32af2fc4f6d8d849557c63dc0c2eacb13a1ea00b0d1ed6adfd47", "id": "0A.7h", "integer": true, "kind": "array", "mistakes": {"f19c496e6f4a7432966ab30ca95c21865902775840438aa486dfe22826d67fcc": "un masque booléen renvoie un tableau à UNE dimension des éléments retenus"}, "shape": [1]}
📝 Ex 0A.7h : réponse enregistrée (array, 0 décimale(s)).
WB_ANSWER {"hash": "f63d91527d4fc72fa9c4c5f8962d0b2882e2390bcee33ecbeeb4b480205160fa", "id": "0A.7i", "kind": "int", "magnitude": 1, "sign": 1}
📝 Ex 0A.7i : réponse enregistrée (int).

**Ex 0A.8 — Broadcasting : compatibles ou non, et quelle forme ?**

In [10]:
wb.record("0A.8a", broadcast((5, 3), (3,)))
wb.record("0A.8b", broadcast((5, 3), (5,)), mistakes={"compare les formes de droite à gauche : 3 et 5 sont différents et aucun ne vaut 1": "(5, 3)"})
wb.record("0A.8c", broadcast((5, 1), (1, 4)))
wb.record("0A.8d", broadcast((2, 1, 3), (4, 1)))
wb.record("0A.8e", broadcast((64, 28, 28), (28, 28)))
wb.record("0A.8f", broadcast((10,), (10, 1)), mistakes={"les axes de taille 1 sont étirés : (10,) se lit (1, 10), et le résultat est un tableau de toutes les différences": "erreur"})
wb.record("0A.8g", broadcast((3, 4), (4, 3)))

WB_ANSWER {"hash": "8d6c5958dbd5c56c3dff35840601fc1d2383c1da1003e605307fd08b83912630", "id": "0A.8a", "kind": "str"}
📝 Ex 0A.8a : réponse enregistrée (str).
WB_ANSWER {"hash": "7f1104adedc6b7f216c0b93570601dcdff852f9d410ee312487b7a1c037c40ee", "id": "0A.8b", "kind": "str", "mistakes": {"9208e363611854953113648982555eb9001700b0d975dd0c91f181770b25d1b4": "compare les formes de droite à gauche : 3 et 5 sont différents et aucun ne vaut 1"}}
📝 Ex 0A.8b : réponse enregistrée (str).
WB_ANSWER {"hash": "07252b4abcc45a5f04199d89d1d9820eb8f0d30241244e70f74631b0da500b3b", "id": "0A.8c", "kind": "str"}
📝 Ex 0A.8c : réponse enregistrée (str).
WB_ANSWER {"hash": "80cb0bd60f033fb6ea866c23fb6161e0f80a5619d7bfee9260468f31ece014c6", "id": "0A.8d", "kind": "str"}
📝 Ex 0A.8d : réponse enregistrée (str).
WB_ANSWER {"hash": "70d3cc572fc13570de41c73a24995180c6ba5006a1c71243ad105a983d5d4ebc", "id": "0A.8e", "kind": "str"}
📝 Ex 0A.8e : réponse enregistrée (str).
WB_ANSWER {"hash": "4dcf165e452010a7188084bf56720b83aa459b7aaa40016b567a807cffe4c1d9", "id": "0A.8f", "kind": "str", "mistakes": {"a2dec3869b43367ced48c3d073defe58bde1a805a3f1d1342e4f415bf626eaa9": "les axes de taille 1 sont étirés : (10,) se lit (1, 10), et le résultat est un tableau de toutes les différences"}}
📝 Ex 0A.8f : réponse enregistrée (str).
WB_ANSWER {"hash": "c0b1da887e7518de416a4c5f00fbf4464dad293e0a86c64f89ed2e8116272a60", "id": "0A.8g", "kind": "str"}
📝 Ex 0A.8g : réponse enregistrée (str).

## Partie A · Prise en main du notebook

Fiche §100.1. Un notebook garde ses variables en mémoire : c'est l'ordre d'exécution qui compte.

### Ex 0A.13 — Ordre d'exécution des cellules : que vaut `x` ? 🔮 ★ ⏱️ 10 min
**Objectif :** comprendre que l'état du noyau dépend de l'ordre dans lequel on exécute les cellules.  
**Prérequis :** fiche §100.1.1 · **Parcours :** R, C

Voici trois cellules, dans cet ordre sur la page :

| Cellule | Code |
|---|---|
| ① | `x = 2` |
| ② | `x = x * 3` |
| ③ | `x = x + 1` |

a) Tu exécutes ①, puis ②, puis ③, puis **encore** ②, puis **encore** ③. Que vaut `x` ?
b) Tu fais ensuite *Redémarrer et tout exécuter* (*Restart and run all*). Que vaut `x` à la fin ?

Écris ton hypothèse **avant** d'exécuter quoi que ce soit, puis réponds dans la cellule suivante.

In [11]:
# a) 2 -> 2 * 3 = 6 -> 6 + 1 = 7 -> 7 * 3 = 21 -> 21 + 1 = 22
# b) restart: memory is empty; "Run all" runs (1), (2), (3) once each -> 7
prediction_0A_13a = 22
prediction_0A_13b = 7

In [12]:
wb.record("0A.13a", prediction_0A_13a, mistakes={"tu as suivi l'ordre de la page, pas l'ordre d'exécution": 7})
wb.record("0A.13b", prediction_0A_13b, mistakes={"après un redémarrage, la mémoire repart de zéro : les exécutions précédentes sont oubliées": 22})

WB_ANSWER {"hash": "f7bccfefb8a513065510d76d9aa3befe7c03adc09ee7471f661f7838fcff6e03", "id": "0A.13a", "kind": "int", "magnitude": 1, "mistakes": {"732dde2139159e93cc40957a19e651e7f63e3333b65696fed614ff85e7039e90": "tu as suivi l'ordre de la page, pas l'ordre d'exécution"}, "sign": 1}
📝 Ex 0A.13a : réponse enregistrée (int).
WB_ANSWER {"hash": "e3e3b2cb668ee34bbc32d3283b1df42521b44f33883651ee39bad9b4740b448d", "id": "0A.13b", "kind": "int", "magnitude": 0, "mistakes": {"71e304f4ac80a6c3fd5c4b82085f5a89eabcfce0fd5836b6cf03be94f6c88750": "après un redémarrage, la mémoire repart de zéro : les exécutions précédentes sont oubliées"}, "sign": 1}
📝 Ex 0A.13b : réponse enregistrée (int).

**Expérience.** Les trois cellules ci-dessous sont ①, ② et ③. Exécute-les **à la main** dans l'ordre de la question a (① ② ③ ② ③), puis lance la dernière cellule, qui affiche `x`. Enfin, fais *Redémarrer et tout exécuter* et regarde la valeur affichée.

In [13]:
x = 2  # cell (1)

In [14]:
x = x * 3  # cell (2)

In [15]:
x = x + 1  # cell (3)

In [16]:
print("x =", x)

x = 7

💡 Un notebook qui ne donne le bon résultat que si l'on exécute les cellules « dans le bon désordre » n'est pas reproductible : avant de le partager, *Restart and run all*.

## Partie B · Python de base : types, structures de données, contrôle du flux

Fiche §100.2 à §100.4. Tout se fait avec du Python « pur » (listes, dictionnaires…) : pandas et NumPy arrivent dans les parties D et E. Les données des manchots sont préparées ci-dessous sous forme de listes ; `None` marque une mesure manquante.

In [17]:
# Data for part B, as plain Python lists (pandas comes in part E)
import pandas as pd

penguins = wb.datasets.load_penguins()          # 344 penguins
penguins_raw = wb.datasets.load_penguins_raw()  # the raw version, 17 columns

species_list = penguins["species"].tolist()
island_list = penguins["island"].tolist()
mass_list = [None if pd.isna(m) else int(m) for m in penguins["body_mass_g"]]         # None = missing
flipper_list = [None if pd.isna(f) else int(f) for f in penguins["flipper_length_mm"]]
print(len(species_list), "penguins; first masses:", mass_list[:5])

344 penguins; first masses: [3750, 3800, 3250, None, 3450]

### Ex 0A.14 — Nombres et f-strings : la fiche d'un manchot 🔨 ★ ⏱️ 13 min
**Objectif :** calculer avec des nombres et mettre en forme un résultat avec une f-string.  
**Prérequis :** Ex 0A.1 · fiche §100.2.1-2 · **Fil rouge :** Penguins · **Parcours :** R, M, C

Un manchot est décrit par quatre variables (déjà écrites dans la cellule).

a) Sa masse en **kilogrammes**, arrondie à 2 décimales (`round`).
b) Sa **fiche**, construite avec une f-string, exactement au format suivant (exemple pour un autre manchot, un Adelie de Dream de 3400 g à la nageoire de 190 mm) : `Adelie (Dream): 3.4 kg, flipper 19.0 cm`. La masse est en kg avec 1 décimale, la nageoire en **cm** avec 1 décimale.
c) Combien de manchots de cette masse peut-on charger, **en entier**, dans un traîneau limité à 50 kg ?
d) Combien de grammes de charge reste-t-il alors ?

In [18]:
species, island, flipper_mm, mass_g = "Gentoo", "Biscoe", 217, 5076

mass_kg = round(mass_g / 1000, 2)
card = f"{species} ({island}): {mass_g / 1000:.1f} kg, flipper {flipper_mm / 10:.1f} cm"
n_penguins = 50_000 // mass_g
remaining_g = 50_000 % mass_g
print(mass_kg, "|", card, "|", n_penguins, "|", remaining_g)

5.08 | Gentoo (Biscoe): 5.1 kg, flipper 21.7 cm | 9 | 4316

In [19]:
wb.record("0A.14a", mass_kg, decimals=2, mistakes={"arrondis à 2 décimales, pas 1": 5.1})
wb.record("0A.14b", card)
wb.record("0A.14c", n_penguins)
wb.record("0A.14d", remaining_g, mistakes={"c'est le reste qui est demandé, pas la masse des manchots chargés": 45684})

WB_ANSWER {"decimals": 2, "hash": "3d316acb57f6cfac9bbbfc3cb40763409dc295c2ef85771f075c9bf786152317", "hash_coarse": "a5257fe4c51313f2ec05ed23dbfdb3dd7c1f9a8f1460319cddac53c14b8c2a9f", "id": "0A.14a", "kind": "float", "magnitude": 0, "mistakes": {"95a90b49ed339b9337b1afad6e28c472bebe57d472d66939a25a49313b67c86a": "arrondis à 2 décimales, pas 1"}, "sign": 1}
📝 Ex 0A.14a : réponse enregistrée (float, 2 décimale(s)).
WB_ANSWER {"hash": "1850c35f05d2802d63a52e7253157179fe2c74f549d8ba00d2ec3248d09c0065", "id": "0A.14b", "kind": "str"}
📝 Ex 0A.14b : réponse enregistrée (str).
WB_ANSWER {"hash": "f8ec5ca64f2e683987926aa4fb1d4f14e7dd9dfc37974e36c84d067ec81e7121", "id": "0A.14c", "kind": "int", "magnitude": 0, "sign": 1}
📝 Ex 0A.14c : réponse enregistrée (int).
WB_ANSWER {"hash": "da669cd4f35f24a65707004107437266e0794bd1b982b3f6030b6cac631716fb", "id": "0A.14d", "kind": "int", "magnitude": 3, "mistakes": {"550ee6f9eac6ca78c1dc0041a2eb077cad16a0ff3de0fb0106bc6926bb5ebcf7": "c'est le reste qui est demandé, pas la masse des manchots chargés"}, "sign": 1}
📝 Ex 0A.14d : réponse enregistrée (int).

### Ex 0A.15 — Chaînes : nettoyer les noms d'espèces de Penguins brut 🔨 ★ ⏱️ 13 min
**Objectif :** transformer du texte avec les méthodes des chaînes (`split`, `find`, `replace`, indices).  
**Prérequis :** Ex 0A.14 · fiche §100.2.2 · **Fil rouge :** Penguins · **Parcours :** C

Dans la version brute du dataset, l'espèce est écrite en toutes lettres : `'Adelie Penguin (Pygoscelis adeliae)'`. La liste `raw_names` contient les trois noms bruts.

Écris deux fonctions :
- `short_name(raw)` renvoie le premier mot : `'Adelie'` ;
- `latin_name(raw)` renvoie le texte **entre les parenthèses** : `'Pygoscelis adeliae'` (indice : `raw.find("(")` et `raw.find(")")`, puis une tranche).

a) `", ".join(short_name(r) for r in raw_names)` (les trois noms courts séparés par une virgule).
b) `latin_name(raw_names[2])`.
c) Le nom latin de la **deuxième** espèce, avec `Pygoscelis` remplacé par `P.` (par exemple `'P. adeliae'` pour la première).

In [20]:
raw_names = penguins_raw["Species"].unique().tolist()
raw_names

['Adelie Penguin (Pygoscelis adeliae)',
 'Gentoo penguin (Pygoscelis papua)',
 'Chinstrap penguin (Pygoscelis antarctica)']

In [21]:
def short_name(raw):
    """Return the first word of a raw species name."""
    return raw.split()[0]


def latin_name(raw):
    """Return the text between the parentheses of a raw species name."""
    start = raw.find("(")
    end = raw.find(")")
    return raw[start + 1:end]


print([short_name(r) for r in raw_names])
print([latin_name(r) for r in raw_names])

['Adelie', 'Gentoo', 'Chinstrap']
['Pygoscelis adeliae', 'Pygoscelis papua', 'Pygoscelis antarctica']

In [22]:
wb.record("0A.15a", ", ".join(short_name(r) for r in raw_names))
wb.record("0A.15b", latin_name(raw_names[2]), mistakes={"garde seulement le texte ENTRE les parenthèses": "(Pygoscelis antarctica)"})
wb.record("0A.15c", latin_name(raw_names[1]).replace("Pygoscelis", "P."))

WB_ANSWER {"hash": "82b6d93abc2a31ff82a5d704ae86de3e17beddafebe13bde2e02e2951489afb6", "id": "0A.15a", "kind": "str"}
📝 Ex 0A.15a : réponse enregistrée (str).
WB_ANSWER {"hash": "eca94b30d657d52f01d981f816c6befe3497635d281ea60f0c5fb873305fa0ce", "id": "0A.15b", "kind": "str", "mistakes": {"20b58502a01ed33a7518277c44bd7222166a26437a0a1e74c9b50661482d765d": "garde seulement le texte ENTRE les parenthèses"}}
📝 Ex 0A.15b : réponse enregistrée (str).
WB_ANSWER {"hash": "7c2736d98db212f3a5fb8ca3f57dabbaf069f8abfdb40c48d9df805fff547339", "id": "0A.15c", "kind": "str"}
📝 Ex 0A.15c : réponse enregistrée (str).

### Ex 0A.16 — Listes : les nageoires de dix manchots 🔨 ★ ⏱️ 13 min
**Objectif :** calculer sur une liste avec `min`, `max`, `sum`, `len`, `sorted` et des indices.  
**Prérequis :** Ex 0A.2 · fiche §100.3.1 · **Fil rouge :** Penguins · **Parcours :** R, M, C

La liste `flippers` contient les longueurs de nageoire (mm) des dix premiers manchots mesurés.

a) L'**étendue** : la plus grande valeur moins la plus petite.
b) La **moyenne**, avec `sum` et `len` (wb.check arrondit à 1 décimale).
c) La liste des **trois plus grandes** valeurs, de la plus grande à la plus petite (`sorted` avec `reverse=True`, puis une tranche).
d) La **médiane** : avec 10 valeurs, c'est la moyenne des 5ᵉ et 6ᵉ valeurs de la liste **triée** (attention : les indices commencent à 0).

In [23]:
flippers = [f for f in flipper_list if f is not None][:10]
flippers

[181, 186, 195, 193, 190, 181, 195, 193, 190, 186]

In [24]:
flipper_range = max(flippers) - min(flippers)
flipper_mean = sum(flippers) / len(flippers)
top3 = sorted(flippers, reverse=True)[:3]
ordered = sorted(flippers)
flipper_median = (ordered[4] + ordered[5]) / 2   # the 5th and 6th values have indices 4 and 5
print(flipper_range, flipper_mean, top3, flipper_median)

14 189.0 [195, 195, 193] 190.0

In [25]:
wb.record("0A.16a", flipper_range)
wb.record("0A.16b", flipper_mean, decimals=1)
wb.record("0A.16c", top3, mistakes={"de la plus grande à la plus petite : sorted(..., reverse=True)": sorted(flippers)[:3]})
wb.record("0A.16d", flipper_median, decimals=1)

WB_ANSWER {"hash": "4809bb1746b4698cb10499df89ad27f168e6b1a27d652ce325b5d9aaad89704f", "id": "0A.16a", "kind": "int", "magnitude": 1, "sign": 1}
📝 Ex 0A.16a : réponse enregistrée (int).
WB_ANSWER {"decimals": 1, "hash": "194c291f8a1f2d62d22faa1c65d0a4d633a289e24f04bc6a02bdb0f1786021b1", "hash_coarse": "a3823b46fddf1f3577c38775b6e4b8a0fb70c09bc8b64486a1685af2b565ace2", "id": "0A.16b", "kind": "float", "magnitude": 2, "sign": 1}
📝 Ex 0A.16b : réponse enregistrée (float, 1 décimale(s)).
WB_ANSWER {"decimals": 0, "element_hashes": ["4247884542f8f19b3858cf5b9077150d5546995cce9a6fb90591980a4405e413", "f050af7e9d07086c7e103742d40ab283b32b4d00def3889405369033a5c2cd00", "9e75690a64d8ec87db78c434ca71dc479c314976650794e21068ea933e5c5d60"], "hash": "1dcca8e096f6f222f5e19eaeea6c8dd8c2323930da0d688222d9f3be4e60e943", "id": "0A.16c", "integer": true, "kind": "array", "mistakes": {"8be9fdac4b87bfd80074701d8e070725e99273b946d1d2711237d5bdd77589bb": "de la plus grande à la plus petite : sorted(..., reverse=True)"}, "shape": [3]}
📝 Ex 0A.16c : réponse enregistrée (array, 0 décimale(s)).
WB_ANSWER {"decimals": 1, "hash": "d2cddad83d45cc9ba136e6405ccda69cb481533f3c99578419d0b557e8fe21e2", "hash_coarse": "dc0f497dbc79503d2ee8a58caf015d3a6a57a6bf3e299cda176b1f90aeb49b93", "id": "0A.16d", "kind": "float", "magnitude": 2, "sign": 1}
📝 Ex 0A.16d : réponse enregistrée (float, 1 décimale(s)).

### Ex 0A.17 — Tuples et déballage : renvoyer et échanger plusieurs valeurs 🔨 ★ ⏱️ 13 min
**Objectif :** renvoyer plusieurs valeurs sous forme de tuple et les récupérer par déballage.  
**Prérequis :** Ex 0A.16 · fiche §100.3.2 · **Parcours :** C

a) Écris `min_max(values)`, qui renvoie le **tuple** `(minimum, maximum)` d'une liste. Vérification : `min_max(flippers)`.
b) Avec `mass_known` (les masses connues), récupère le minimum et le maximum par déballage (`low, high = ...`) : que vaut `high - low` ?
c) Échange les valeurs de `first_species` et `second_species` **en une seule ligne**, sans variable intermédiaire. Vérification : `first_species + "/" + second_species`.
d) Avec `head, *middle, tail = flippers`, combien d'éléments contient `middle` ?

In [26]:
mass_known = [m for m in mass_list if m is not None]

In [27]:
def min_max(values):
    """Return the tuple (smallest value, largest value) of a list."""
    return min(values), max(values)


low, high = min_max(mass_known)
mass_span = high - low

first_species, second_species = "Adelie", "Gentoo"
first_species, second_species = second_species, first_species
swapped = first_species + "/" + second_species
head, *middle, tail = flippers
n_middle = len(middle)
print(min_max(flippers), mass_span, first_species, second_species, n_middle)

(181, 195) 3600 Gentoo Adelie 8

In [28]:
wb.record("0A.17a", min_max(flippers))
wb.record("0A.17b", mass_span)
wb.record("0A.17c", swapped, mistakes={"les deux variables n'ont pas été échangées": "Adelie/Gentoo"})
wb.record("0A.17d", n_middle)

WB_ANSWER {"decimals": 0, "element_hashes": ["4934c7d7b07ccde96336c7121a2c961d0b93162f0fbc0998530fc29cd7a5ee05", "36dbcc747780fcbd85cc78bde113b82576e51dfa0822301f26086693676c609b"], "hash": "2819d22871cf16cafdc5dc441a7e509eb371a41095f5acdbade2d69720fcb7b1", "id": "0A.17a", "integer": true, "kind": "array", "shape": [2]}
📝 Ex 0A.17a : réponse enregistrée (array, 0 décimale(s)).
WB_ANSWER {"hash": "db5e08e4e42f3c03e311981bedafc6f9198db912d00393ea13279db6f2d968f2", "id": "0A.17b", "kind": "int", "magnitude": 3, "sign": 1}
📝 Ex 0A.17b : réponse enregistrée (int).
WB_ANSWER {"hash": "45aca69a51d4919e853d1831841cded868e02fde8921888e656eb360306b297a", "id": "0A.17c", "kind": "str", "mistakes": {"b99b74d53b1c355f149dbbc4f8bb9658315e29357a86b1f75643c31b58883be3": "les deux variables n'ont pas été échangées"}}
📝 Ex 0A.17c : réponse enregistrée (str).
WB_ANSWER {"hash": "894c60fcfd6535e8c74b1430281bfa1afefae980ce30c28c7bc437a3634b6e5a", "id": "0A.17d", "kind": "int", "magnitude": 0, "sign": 1}
📝 Ex 0A.17d : réponse enregistrée (int).

### Ex 0A.18 — Dictionnaires : une fiche par espèce 🔨 ★ ⏱️ 15 min
**Objectif :** regrouper des valeurs par clé dans un dictionnaire, puis en tirer une statistique.  
**Prérequis :** Ex 0A.16 · fiche §100.3.3 · **Fil rouge :** Penguins · **Parcours :** R, M, C

On veut, pour chaque espèce, la liste de ses masses connues, puis la masse moyenne de chaque espèce.

Complète le squelette : pour chaque manchot, ajoute sa masse à la liste de son espèce (crée la liste la première fois qu'une espèce apparaît : `masses_by_species[species] = []`, ou utilise `setdefault`), puis remplis `mean_by_species`.

a) Le nombre de clés de `masses_by_species`.
b) Le nombre de masses connues pour les Adelie.
c) La masse moyenne des Chinstrap (wb.check arrondit à 0 décimale).
d) L'espèce dont la masse moyenne est la plus élevée (une chaîne).

In [29]:
masses_by_species = {}
for species, mass in zip(species_list, mass_list):
    if mass is None:
        continue
    masses_by_species.setdefault(species, []).append(mass)

mean_by_species = {}
for species, masses in masses_by_species.items():
    mean_by_species[species] = sum(masses) / len(masses)

n_keys = len(masses_by_species)
n_adelie = len(masses_by_species["Adelie"])
chinstrap_mean = mean_by_species["Chinstrap"]
heaviest = None
for species, mean in mean_by_species.items():
    if heaviest is None or mean > mean_by_species[heaviest]:
        heaviest = species
print(n_keys, n_adelie, round(chinstrap_mean), heaviest)

3 151 3733 Gentoo

In [30]:
wb.record("0A.18a", n_keys)
wb.record("0A.18b", n_adelie, mistakes={"compte seulement les masses connues (saute les None)": 152})
wb.record("0A.18c", chinstrap_mean, decimals=0)
wb.record("0A.18d", heaviest)

WB_ANSWER {"hash": "4ed81523cbb17f1cb447f1444e89f1d824602372bd67fd92d14d9272bfe3f8d4", "id": "0A.18a", "kind": "int", "magnitude": 0, "sign": 1}
📝 Ex 0A.18a : réponse enregistrée (int).
WB_ANSWER {"hash": "17aa394a0b235ae326ef5155a2b4d9b3f22322773350ce93ede751af896f9f0d", "id": "0A.18b", "kind": "int", "magnitude": 2, "mistakes": {"26bb303b7df78c0d777b1f3b5a313e627522e0d396b990c0cba0049b1d96a8a6": "compte seulement les masses connues (saute les None)"}, "sign": 1}
📝 Ex 0A.18b : réponse enregistrée (int).
WB_ANSWER {"decimals": 0, "hash": "0ad97a6bc45e9528fc5470aa19f18829d4269034be46654182b07e2d863ab5c9", "id": "0A.18c", "kind": "float", "magnitude": 3, "sign": 1}
📝 Ex 0A.18c : réponse enregistrée (float, 0 décimale(s)).
WB_ANSWER {"hash": "3bf1726838d197878106db17f23d0b204a25bde372f33f0fa1fa9a4effd2c190", "id": "0A.18d", "kind": "str"}
📝 Ex 0A.18d : réponse enregistrée (str).

### Ex 0A.19 — Ensembles : quelles espèces sur quelles îles ? 🔨 ★ ⏱️ 13 min
**Objectif :** dédoublonner et croiser des informations avec des ensembles.  
**Prérequis :** Ex 0A.18 · fiche §100.3.4 · **Fil rouge :** Penguins · **Parcours :** C

`pairs` est la liste des couples `(espèce, île)` des 344 manchots. La première réponse est donnée en exemple.

a) L'ensemble des îles où vivent des Adelie (déjà écrit).
b) L'ensemble des îles où vivent des Gentoo.
c) L'ensemble des îles où vivent **à la fois** des Adelie et des Chinstrap (opérateur `&`).
d) Le nombre de couples `(espèce, île)` **différents**.

In [31]:
pairs = list(zip(species_list, island_list))
pairs[:3]

[('Adelie', 'Torgersen'), ('Adelie', 'Torgersen'), ('Adelie', 'Torgersen')]

In [32]:
adelie_islands = {island for species, island in pairs if species == "Adelie"}
gentoo_islands = {island for species, island in pairs if species == "Gentoo"}
chinstrap_islands = {island for species, island in pairs if species == "Chinstrap"}
both_islands = adelie_islands & chinstrap_islands
n_distinct_pairs = len(set(pairs))
print(sorted(adelie_islands), sorted(gentoo_islands), both_islands, n_distinct_pairs)

['Biscoe', 'Dream', 'Torgersen'] ['Biscoe'] {'Dream'} 5

In [33]:
wb.record("0A.19a", adelie_islands, ordered=False)
wb.record("0A.19b", gentoo_islands, ordered=False)
wb.record("0A.19c", both_islands, ordered=False, mistakes={"& garde ce qui est commun aux deux ensembles ; | les réunit": adelie_islands | chinstrap_islands})
wb.record("0A.19d", n_distinct_pairs, mistakes={"un ensemble ne garde qu'un exemplaire de chaque couple : utilise set(pairs)": 344})

WB_ANSWER {"hash": "2142c97d8a7c361d9dbbfeb24b554b3bbff9e3f6da706b4341bfe395e3def7bd", "id": "0A.19a", "kind": "set"}
📝 Ex 0A.19a : réponse enregistrée (set).
WB_ANSWER {"hash": "af0ecbaf14096e2ac8101f148fea599d95607af095d21fc0fc2c89955811a30f", "id": "0A.19b", "kind": "set"}
📝 Ex 0A.19b : réponse enregistrée (set).
WB_ANSWER {"hash": "f72c2a2fee4df7ad1a8ca33bd1d5048949597687ed3f21bce59ecf867537dfdf", "id": "0A.19c", "kind": "set", "mistakes": {"b31ec9df28262db92b8a1525260849508f7025f64b72c97468559c0653780020": "& garde ce qui est commun aux deux ensembles ; | les réunit"}}
📝 Ex 0A.19c : réponse enregistrée (set).
WB_ANSWER {"hash": "86f3979014cc738c2b9680df4e35fc5a177403847e305460227d955cabeefd77", "id": "0A.19d", "kind": "int", "magnitude": 0, "mistakes": {"fcf3ad2e330ea61912a6d9f090a78da4531fb29b84fb73ae3e9837cc8871686f": "un ensemble ne garde qu'un exemplaire de chaque couple : utilise set(pairs)"}, "sign": 1}
📝 Ex 0A.19d : réponse enregistrée (int).

### Ex 0A.20 — Conditions : classer un manchot selon sa masse 🔨 ★ ⏱️ 13 min
**Objectif :** écrire une suite de tests `if` / `elif` / `else` dans le bon ordre, en traitant le cas « valeur manquante ».  
**Prérequis :** Ex 0A.14 · fiche §100.4.1 · **Fil rouge :** Penguins · **Parcours :** R, M, C

Écris `mass_category(mass_g)`, qui renvoie :
- `"unknown"` si `mass_g` vaut `None` (masse manquante) ;
- `"light"` en dessous de 3500 g ;
- `"medium"` de 3500 g (inclus) à 4500 g (exclu) ;
- `"heavy"` à partir de 4500 g.

a) `mass_category(3500)` · b) `mass_category(None)` · c) le nombre de manchots `"heavy"` parmi les 344 · d) le nombre de `"light"`.

In [34]:
def mass_category(mass_g):
    """Return "unknown", "light", "medium" or "heavy" for a mass in grams (or None)."""
    if mass_g is None:          # test the missing value FIRST: None < 3500 would raise a TypeError
        return "unknown"
    if mass_g < 3500:
        return "light"
    elif mass_g < 4500:
        return "medium"
    else:
        return "heavy"


categories = [mass_category(m) for m in mass_list]
print(mass_category(3500), mass_category(None), categories.count("heavy"), categories.count("light"))

medium unknown 118 71

In [35]:
wb.record("0A.20a", mass_category(3500), mistakes={"3500 g est inclus dans « medium » : le test est mass_g < 3500 pour « light »": "light"})
wb.record("0A.20b", mass_category(None))
wb.record("0A.20c", categories.count("heavy"))
wb.record("0A.20d", categories.count("light"))

WB_ANSWER {"hash": "a289e6eca64d049fb5c461d571746b1f944e7a2b6475844a7ee1735edf10db2a", "id": "0A.20a", "kind": "str", "mistakes": {"b68dca1b07c3d892bf344533c08a9da6bce9b94b9043d564d2566b806a227801": "3500 g est inclus dans « medium » : le test est mass_g < 3500 pour « light »"}}
📝 Ex 0A.20a : réponse enregistrée (str).
WB_ANSWER {"hash": "d4872cac2e8a7296746200e198f9c97ae7220a834012eb33dd741a6bc22691b9", "id": "0A.20b", "kind": "str"}
📝 Ex 0A.20b : réponse enregistrée (str).
WB_ANSWER {"hash": "630bcc123b805d59f447d08cee582b1b2bfa9666625f9fab1d2fc78449268412", "id": "0A.20c", "kind": "int", "magnitude": 2, "sign": 1}
📝 Ex 0A.20c : réponse enregistrée (int).
WB_ANSWER {"hash": "772920d1ea8c3ad847f0d3e7a583406a574e13d7bb3f0982ba1f843c4c8f85ca", "id": "0A.20d", "kind": "int", "magnitude": 1, "sign": 1}
📝 Ex 0A.20d : réponse enregistrée (int).

### Ex 0A.21 — Boucles : `for`, `range`, `enumerate`, `zip` et `while` 🔨 ★ ⏱️ 15 min
**Objectif :** choisir la bonne boucle pour parcourir des données ou répéter un calcul.  
**Prérequis :** Ex 0A.3, Ex 0A.20 · fiche §100.4.2 · **Fil rouge :** Penguins · **Parcours :** R, M, C

a) Avec `zip(species_list, mass_list)` : la masse totale des Chinstrap, en **kg** (saute les masses manquantes ; wb.check arrondit à 2 décimales).
b) Avec `enumerate(mass_list)` : l'**indice** du premier manchot de plus de 6000 g (utilise `break`).
c) Avec `while` : une colonie de 344 manchots grandit de 8 % par an (`n = n * 1.08`). Au bout de combien d'**années entières** dépasse-t-elle 1000 manchots ?
d) Avec `range` : la somme des nombres **pairs** de 0 à 100 inclus.
e) L'indice du premier manchot dont la nageoire est manquante (`None`) dans `flipper_list`.

In [36]:
chinstrap_total_kg = 0
for species, mass in zip(species_list, mass_list):
    if species == "Chinstrap" and mass is not None:
        chinstrap_total_kg += mass / 1000

first_heavy_index = None
for i, mass in enumerate(mass_list):
    if mass is not None and mass > 6000:
        first_heavy_index = i
        break

colony, years = 344, 0
while colony <= 1000:
    colony = colony * 1.08
    years += 1

even_sum = 0
for k in range(0, 101, 2):     # 0, 2, ..., 100 (the stop value 101 is excluded)
    even_sum += k

first_missing = flipper_list.index(None)
print(round(chinstrap_total_kg, 2), first_heavy_index, years, even_sum, first_missing)

253.85 169 14 2550 3

In [37]:
wb.record("0A.21a", chinstrap_total_kg, decimals=2)
wb.record("0A.21b", first_heavy_index)
wb.record("0A.21c", years, mistakes={"compte les années jusqu'à DÉPASSER 1000 : la boucle tourne tant que n <= 1000": 13})
wb.record("0A.21d", even_sum, mistakes={"range(0, 100, 2) s'arrête à 98 : la fin est exclue": 2450})
wb.record("0A.21e", first_missing)

WB_ANSWER {"decimals": 2, "hash": "d624164c86c7dedf56993964744b481be8c08bc492cdcacae95b20ea9e020ecd", "hash_coarse": "3821963e9e0e5387acef723c6a44508053bd35e1d9439777ab652100641ef689", "id": "0A.21a", "kind": "float", "magnitude": 2, "sign": 1}
📝 Ex 0A.21a : réponse enregistrée (float, 2 décimale(s)).
WB_ANSWER {"hash": "667fb6183a5b6b1005e3dafd098158ec7e901429cf9f706c3b30fba775002f36", "id": "0A.21b", "kind": "int", "magnitude": 2, "sign": 1}
📝 Ex 0A.21b : réponse enregistrée (int).
WB_ANSWER {"hash": "4b30df4421c6bd32475ed1f3d4404dc46ad9e01a22661c7c83e0209c3f879f9e", "id": "0A.21c", "kind": "int", "magnitude": 1, "mistakes": {"bfd5f05473c9073635a0f716d6233d9852d6d672ab7dd442a6818256641ee310": "compte les années jusqu'à DÉPASSER 1000 : la boucle tourne tant que n <= 1000"}, "sign": 1}
📝 Ex 0A.21c : réponse enregistrée (int).
WB_ANSWER {"hash": "1eb34e88f64e39333641f3facefbe55663532c6ca3a857b9573982384968b5cd", "id": "0A.21d", "kind": "int", "magnitude": 3, "mistakes": {"86e5f3b0ae9f4a36af687b65e50cdd15e14fe58981617439013821f8e12c553e": "range(0, 100, 2) s'arrête à 98 : la fin est exclue"}, "sign": 1}
📝 Ex 0A.21d : réponse enregistrée (int).
WB_ANSWER {"hash": "a49057ea80a214183c8d9284a247ce896ef1e3c921f8e25c680ef72d33d7cefe", "id": "0A.21e", "kind": "int", "magnitude": 0, "sign": 1}
📝 Ex 0A.21e : réponse enregistrée (int).

### Ex 0A.22 — Compréhensions : filtrer et transformer en une ligne 🔨 ★ ⏱️ 15 min
**Objectif :** remplacer une boucle d'accumulation par une compréhension de liste, de dictionnaire ou d'ensemble.  
**Prérequis :** Ex 0A.21 · fiche §100.4.3 · **Fil rouge :** Penguins · **Parcours :** R, M, C

Une ligne par réponse, avec une compréhension.

a) La liste des masses **en kg** des manchots d'au moins 6000 g (`heavy_kg`), puis sa somme (wb.check arrondit à 2 décimales).
b) Le dictionnaire `{espèce: nombre de manchots}` (`counts` : parcours `sorted(set(species_list))` et utilise `species_list.count`), puis sa valeur pour `"Chinstrap"`.
c) La liste des longueurs de nageoire des Gentoo en **cm** (`gentoo_cm`, via `zip(species_list, flipper_list)`, en sautant les `None`), puis sa plus grande valeur.
d) L'ensemble des noms d'îles en **majuscules**.

In [38]:
heavy_kg = [m / 1000 for m in mass_list if m is not None and m >= 6000]
counts = {sp: species_list.count(sp) for sp in sorted(set(species_list))}
gentoo_cm = [f / 10 for sp, f in zip(species_list, flipper_list) if sp == "Gentoo" and f is not None]
islands_upper = {island.upper() for island in island_list}
heavy_kg_total = sum(heavy_kg)
chinstrap_count = counts["Chinstrap"]
gentoo_cm_max = max(gentoo_cm)
print(heavy_kg, counts, gentoo_cm_max, islands_upper)

[6.3, 6.05, 6.0, 6.0] {'Adelie': 152, 'Chinstrap': 68, 'Gentoo': 124} 23.1 {'TORGERSEN', 'BISCOE', 'DREAM'}

In [39]:
wb.record("0A.22a", heavy_kg_total, decimals=2)
wb.record("0A.22b", chinstrap_count)
wb.record("0A.22c", gentoo_cm_max, decimals=1, mistakes={"la réponse est en cm : divise les mm par 10": gentoo_cm_max * 10})
wb.record("0A.22d", islands_upper, ordered=False)

WB_ANSWER {"decimals": 2, "hash": "14673f0adc59ec55799f4fc97605d7bbbe920b1cae4d73ff26bed646bb21b97f", "hash_coarse": "89b6317fb0d9e1d16052935aaea173fd4960f5126e536e4f8929d5a5fd34ecfe", "id": "0A.22a", "kind": "float", "magnitude": 1, "sign": 1}
📝 Ex 0A.22a : réponse enregistrée (float, 2 décimale(s)).
WB_ANSWER {"hash": "658fb4105a7207a7dbdfb7bb38f36553204fe5aa717233adfb4891d7c5bcd6e8", "id": "0A.22b", "kind": "int", "magnitude": 1, "sign": 1}
📝 Ex 0A.22b : réponse enregistrée (int).
WB_ANSWER {"decimals": 1, "hash": "bd022432c8da316b65cd4a5c3039b27d66b94a76bcf3497aa9e12da0856fe79c", "hash_coarse": "45735acba51063ac05383b68e929839c0370397f27c5bdcda93b0c954ce0c38b", "id": "0A.22c", "kind": "float", "magnitude": 1, "mistakes": {"861747410e0c8268e726d3b712cb1763c9204f236c8d0d8bb90b73c6d42938ae": "la réponse est en cm : divise les mm par 10"}, "sign": 1}
📝 Ex 0A.22c : réponse enregistrée (float, 1 décimale(s)).
WB_ANSWER {"hash": "17a04fbcef0abef97cab54b4114542b00b8fb43822cbbe19052c293d781fd07c", "id": "0A.22d", "kind": "set"}
📝 Ex 0A.22d : réponse enregistrée (set).

## Partie C · Fonctions, modules, erreurs et premier module mylearn

Fiche §100.5.1, §100.6.1-2 et §100.11.5.

### Ex 0A.23 — Tes premières fonctions : paramètres, valeurs par défaut, `return` 🔨 ★ ⏱️ 15 min
**Objectif :** écrire des fonctions avec des paramètres obligatoires et par défaut, qui **renvoient** un résultat.  
**Prérequis :** Ex 0A.22 · fiche §100.5.1 · **Fil rouge :** Penguins · **Parcours :** R, M, C

Écris deux fonctions :
- `flipper_per_kg(flipper_mm, mass_g)` : la longueur de nageoire (mm) par kilogramme de masse ;
- `describe(species, mass_g, unit="kg", decimals=1)` : une chaîne `"<espèce>: <masse> <unité>"`. Avec `unit="kg"`, la masse est en kg arrondie à `decimals` décimales ; avec `unit="g"`, c'est la masse en grammes, **entière**. Toute autre unité lève une `ValueError`.

a) `flipper_per_kg(181, 3750)` (wb.check arrondit à 2 décimales) · b) `describe("Gentoo", 5076)` · c) `describe("Gentoo", 5076, unit="g")` · d) `describe("Adelie", 3750, decimals=2)`.

In [40]:
def flipper_per_kg(flipper_mm, mass_g):
    """Return the flipper length (mm) per kilogram of body mass."""
    return flipper_mm / (mass_g / 1000)


def describe(species, mass_g, unit="kg", decimals=1):
    """Return "<species>: <mass> <unit>" with the mass in kg (rounded) or in g (integer)."""
    if unit == "kg":
        value = round(mass_g / 1000, decimals)
    elif unit == "g":
        value = int(mass_g)
    else:
        raise ValueError(f"unit must be 'kg' or 'g', not {unit!r}")
    return f"{species}: {value} {unit}"


print(flipper_per_kg(181, 3750), describe("Gentoo", 5076), describe("Gentoo", 5076, unit="g"),
      describe("Adelie", 3750, decimals=2), sep=" | ")

48.266666666666666 | Gentoo: 5.1 kg | Gentoo: 5076 g | Adelie: 3.75 kg

In [41]:
wb.record("0A.23a", flipper_per_kg(181, 3750), decimals=2, mistakes={"convertis d'abord la masse en kg": 181 / 3750})
wb.record("0A.23b", describe("Gentoo", 5076))
wb.record("0A.23c", describe("Gentoo", 5076, unit="g"))
wb.record("0A.23d", describe("Adelie", 3750, decimals=2))

WB_ANSWER {"decimals": 2, "hash": "539ba88ff3194ff272b2557e0ec9ed4fcfe1243bc63547dc2a6e21e97527b9b5", "hash_coarse": "68293f1e2216dfaf5fb86a54961edd2ccbb1c738c5f7cafde0056dc86d32ed6c", "id": "0A.23a", "kind": "float", "magnitude": 1, "mistakes": {"fa268d8393373f762147f2f26c8f0a71f4369bf5516b02ffa68fa53514efef7e": "convertis d'abord la masse en kg"}, "sign": 1}
📝 Ex 0A.23a : réponse enregistrée (float, 2 décimale(s)).
WB_ANSWER {"hash": "f73c66b86112e31b5a0dae6776647935a922f8c33d14c35b634ae7a4331f0238", "id": "0A.23b", "kind": "str"}
📝 Ex 0A.23b : réponse enregistrée (str).
WB_ANSWER {"hash": "6784e5f8eaa0917f31277f648c5b2cd110dbb4f4e30e3fe681f3766b5f158b62", "id": "0A.23c", "kind": "str"}
📝 Ex 0A.23c : réponse enregistrée (str).
WB_ANSWER {"hash": "a00a88919f79eab98789b9b19c6408000dcd4e2d68caa55f8104e80d4cc79823", "id": "0A.23d", "kind": "str"}
📝 Ex 0A.23d : réponse enregistrée (str).

### Ex 0A.24 — Importer des modules : `math`, `random`, `statistics` et `Counter` 🔨 ★ ⏱️ 13 min
**Objectif :** trouver et utiliser la bonne fonction de la bibliothèque standard plutôt que la réécrire.  
**Prérequis :** Ex 0A.23 · fiche §100.6.1 et §100.3.5 · **Fil rouge :** Penguins · **Parcours :** R, M, C

Importe ce qu'il faut (`import math`, `import statistics`, `from collections import Counter`…) dans la cellule, puis :

a) Le nombre de mini-lots de 50 manchots nécessaires pour les 344 (`math.ceil`).
b) La médiane des dix nageoires `flippers` (`statistics.median`).
c) L'île la plus fréquente et d) son nombre de manchots (`Counter(island_list).most_common`).
e) L'écart-type de `mass_known` (`statistics.stdev` ; wb.check arrondit à 1 décimale).

La dernière cellule simule dix lancers de dé avec `random` : exécute-la deux fois, puis retire la ligne `random.seed(0)` et recommence. Qu'observes-tu ?

In [42]:
import math
import statistics
from collections import Counter

n_batches = math.ceil(344 / 50)
median_flipper = statistics.median(flippers)
top_island, top_count = Counter(island_list).most_common(1)[0]
mass_stdev = statistics.stdev(mass_known)
print(n_batches, median_flipper, top_island, top_count, round(mass_stdev, 1))

7 190.0 Biscoe 168 802.0

In [43]:
wb.record("0A.24a", n_batches, mistakes={"le dernier lot incomplet compte aussi : math.ceil, pas //": 6})
wb.record("0A.24b", median_flipper, decimals=1)
wb.record("0A.24c", top_island)
wb.record("0A.24d", top_count)
wb.record("0A.24e", mass_stdev, decimals=1)

WB_ANSWER {"hash": "a449472a26c043b6f426e4eb639f1e2834678ce977e21fc37df4d8abc923cac4", "id": "0A.24a", "kind": "int", "magnitude": 0, "mistakes": {"63051ffed5c8d417aa20e88117cac4471214f3bb4d2868cb1bdd25d4291821be": "le dernier lot incomplet compte aussi : math.ceil, pas //"}, "sign": 1}
📝 Ex 0A.24a : réponse enregistrée (int).
WB_ANSWER {"decimals": 1, "hash": "7a533073d840953458d72959ab9739823296c61ad585eb3f4bb88cc28ace9e5e", "hash_coarse": "367bcd3afe0aec208aa9594c53282d66312d64be83538d12b85a217011ee2115", "id": "0A.24b", "kind": "float", "magnitude": 2, "sign": 1}
📝 Ex 0A.24b : réponse enregistrée (float, 1 décimale(s)).
WB_ANSWER {"hash": "a0c14cdfc42093e7eef57c53946d5714ccbaa73c343d861f2c1c56ed76a29d66", "id": "0A.24c", "kind": "str"}
📝 Ex 0A.24c : réponse enregistrée (str).
WB_ANSWER {"hash": "4bb76a928bcabe9c376f3eb168909794559b40430b8756e86438fe9ae7742979", "id": "0A.24d", "kind": "int", "magnitude": 2, "sign": 1}
📝 Ex 0A.24d : réponse enregistrée (int).
WB_ANSWER {"decimals": 1, "hash": "b666d23b1a7084e0b3c6666ecd60e1dd6a48524b3619ec4a97c420a102f8b1c5", "hash_coarse": "1cae2547d8452dbaf98a60fff5f83bb6d929235947ef6ebd18ed682e7581c038", "id": "0A.24e", "kind": "float", "magnitude": 2, "sign": 1}
📝 Ex 0A.24e : réponse enregistrée (float, 1 décimale(s)).

In [44]:
import random

random.seed(0)
print([random.randint(1, 6) for _ in range(10)])

[4, 4, 1, 3, 5, 4, 4, 3, 4, 3]

💡 Avec la même graine, `random` redonne exactement la même suite : c'est ce qui rend une expérience reproductible (fiche §100.8.7).

### Ex 0A.25 — Exceptions : lever une `ValueError` et la rattraper 🔨 ★ ⏱️ 15 min
**Objectif :** refuser une entrée invalide avec un message clair, et traiter l'erreur là où on sait quoi faire.  
**Prérequis :** Ex 0A.23 · fiche §100.6.2 · **Parcours :** R, M, C

Des masses ont été saisies à la main, sous forme de texte (`texts`). Certaines sont invalides.

- `parse_mass(text)` : retire les espaces autour, lève `ValueError("empty mass")` si le texte est vide, convertit en `float` (ce qui lève déjà une `ValueError` pour `"NA"` ou `"3,450"`), et lève `ValueError("negative mass")` si le résultat est négatif. Elle renvoie la masse.
- `parse_all(texts)` : renvoie la liste des masses, avec `None` à la place de chaque texte invalide (`try` / `except ValueError`).

a) Le nombre de masses valides · b) leur somme · c) vérifié automatiquement : `parse_mass("")` doit lever une `ValueError` (la cellule de vérification rattrape l'exception et contrôle son nom).

In [45]:
texts = ["3750", " 3800 ", "", "3,450", "-12", "4.2e3", "NA", "5076"]

In [46]:
def parse_mass(text):
    """Convert a text to a mass in grams; raise ValueError if it is empty, not a number or negative."""
    text = text.strip()
    if text == "":
        raise ValueError("empty mass")
    mass = float(text)           # raises ValueError for "NA" or "3,450"
    if mass < 0:
        raise ValueError("negative mass")
    return mass


def parse_all(texts):
    """Parse every text; invalid ones become None."""
    masses = []
    for text in texts:
        try:
            masses.append(parse_mass(text))
        except ValueError:
            masses.append(None)
    return masses


parsed = parse_all(texts)
valid = [m for m in parsed if m is not None]
print(parsed)

[3750.0, 3800.0, None, None, None, 4200.0, None, 5076.0]

In [47]:
wb.record("0A.25a", len(valid), mistakes={"une masse négative doit être refusée": 5})
wb.record("0A.25b", sum(valid), decimals=1, mistakes={"4.2e3 est un nombre valide (4200.0)": sum(valid) - 4200})
wb.record("0A.25c", "ValueError")

WB_ANSWER {"hash": "0e484875db398a476faba0c1011a8f898de494441a2cdce9934728bd0c9619fe", "id": "0A.25a", "kind": "int", "magnitude": 0, "mistakes": {"938db1cbb38a70cd0de9a77966ce8cf489fa77fd9b71066d68959f9cfa50e401": "une masse négative doit être refusée"}, "sign": 1}
📝 Ex 0A.25a : réponse enregistrée (int).
WB_ANSWER {"decimals": 1, "hash": "5b5b9e00387fa37b8403e701dacebb4f2a1b57fe22507dafcb35c02da583c554", "hash_coarse": "bea7fa768d4746997dfb3f63a225e660f661506e0e926732163069aa0f37af1c", "id": "0A.25b", "kind": "float", "magnitude": 4, "mistakes": {"73a0c1e1312c5117cf3fb4090cf574c31f40d440cc10726f124e7651b863effc": "4.2e3 est un nombre valide (4200.0)"}, "sign": 1}
📝 Ex 0A.25b : réponse enregistrée (float, 1 décimale(s)).
WB_ANSWER {"hash": "5aec1fa640663bf0d1815905a940f9182d50ee7f9b1d45f9b18a42e71709453e", "id": "0A.25c", "kind": "str"}
📝 Ex 0A.25c : réponse enregistrée (str).

### Ex 0A.26 — Ton premier module mylearn : `mean` et son test 🔨 ★ ⏱️ 15 min
**Objectif :** compléter une fonction de mylearn à partir de son squelette et la valider avec pytest.  
**Prérequis :** Ex 0A.25 · fiche §100.11.5 et §100.11.3 · **Parcours :** R, M, C

C'est ton premier contact avec **mylearn**, ta librairie.

1. Si ce n'est pas fait : `python tools/start_chapter.py 0A` (ou `--init`) crée `mon_travail/mylearn/`.
2. Ouvre `mon_travail/mylearn/_example.py`. Lis la docstring de `mean` : elle dit ce que la fonction doit faire, y compris refuser une liste vide.
3. Remplace la ligne `raise NotImplementedError(...)` par ton code, **enregistre** le fichier.
4. Redémarre le noyau (le module est chargé au setup), relance la cellule de setup, puis les deux cellules ci-dessous : la première vérifie ta fonction sur les dix nageoires (wb.check arrondit à 2 décimales), la seconde lance les **tests** (`tests/test_example_mylearn.py`) : ils doivent tous passer (`5 passed`).

In [48]:
print(mylearn._example.mean(flippers))

# the same tests, run on the reference implementation (--impl=ref)
result = subprocess.run(
    [sys.executable, "-m", "pytest", "tests/test_example_mylearn.py", "--impl=ref", "-q", "-p", "no:cacheprovider",
     "--color=no"],
    cwd=ROOT, capture_output=True, text=True,
)
print(result.stdout.strip().splitlines()[-1])

189.0

5 passed in 0.02s

In [49]:
wb.record("0A.26", mylearn._example.mean(flippers), decimals=2)

WB_ANSWER {"decimals": 2, "hash": "69adf1819cde158bb54ae4c7bb2e8fa5814710bd0e961c555fe2a927cd630240", "hash_coarse": "bb93d386e9ab60554f3e932ef459c51df054cc6de9b68376367834bde8a39d11", "id": "0A.26", "kind": "float", "magnitude": 2, "sign": 1}
📝 Ex 0A.26 : réponse enregistrée (float, 2 décimale(s)).

💡 Dans le notebook de solutions, `mylearn` est la **référence** : les tests y passent donc. Dans ton notebook, c'est **ton** code qui est testé.

## Partie D · Premiers pas NumPy

Fiche §100.8.1 à §100.8.3 et §100.8.7. On part de `table`, une liste de 333 listes de 4 mesures (bec, profondeur du bec, nageoire, masse) : les manchots sans valeur manquante.

In [50]:
import numpy as np

numeric_cols = ["bill_length_mm", "bill_depth_mm", "flipper_length_mm", "body_mass_g"]
table = penguins.dropna()[numeric_cols].values.tolist()   # 333 rows of 4 numbers (plain Python lists)
table[:2]

[[39.1, 18.7, 181.0, 3750.0], [39.5, 17.4, 186.0, 3800.0]]

### Ex 0A.27 — Premiers arrays NumPy : `dtype`, `shape`, `ndim` 📦 ★ ⏱️ 13 min
**Objectif :** créer un array et lire ses attributs de base.  
**Prérequis :** Ex 0A.16 · fiche §100.8.1 · **Fil rouge :** Penguins · **Parcours :** R, M, C

Crée `X = np.array(table)`, puis donne :

a) sa forme · b) le **nom** de son type d'éléments (`X.dtype.name`, une chaîne) · c) son nombre de dimensions · d) son nombre total d'éléments · e) la 4ᵉ valeur (indice 3) de `np.linspace(0, 1, 11)`.

In [51]:
X = np.array(table)
x_shape, x_dtype, x_ndim, x_size = X.shape, X.dtype.name, X.ndim, X.size
fourth = np.linspace(0, 1, 11)[3]
print(x_shape, x_dtype, x_ndim, x_size, fourth)

(333, 4) float64 2 1332 0.30000000000000004

In [52]:
wb.record("0A.27a", x_shape, mistakes={"(lignes, colonnes) : 333 manchots, 4 mesures": (4, 333)})
wb.record("0A.27b", x_dtype)
wb.record("0A.27c", x_ndim)
wb.record("0A.27d", x_size)
wb.record("0A.27e", fourth, decimals=1)

WB_ANSWER {"decimals": 0, "element_hashes": ["74c55631f6d05bd05c93749d9ab11584994f57da1963bd05ed020396a976906f", "4b13c72a77e824dc72a61b1a5c1484b03fb15d9ab5cb173e364091d365775b63"], "hash": "59130f0d127fad63177be963288f5c5217c33961813211be85d746ddf86b9835", "id": "0A.27a", "integer": true, "kind": "array", "mistakes": {"5f250e548d1c6cd28f2f5b141cc1f64fb2ca2d34a861a198fc52c300fc606436": "(lignes, colonnes) : 333 manchots, 4 mesures"}, "shape": [2]}
📝 Ex 0A.27a : réponse enregistrée (array, 0 décimale(s)).
WB_ANSWER {"hash": "c2c756562d14d97f10c369767bf1a0c9a87956f85759bbc22b53e77f16da5ba4", "id": "0A.27b", "kind": "str"}
📝 Ex 0A.27b : réponse enregistrée (str).
WB_ANSWER {"hash": "a30ed2dfd46a70a954804a2b81ed7af01b5fbddea21a0898cac0048d241b2368", "id": "0A.27c", "kind": "int", "magnitude": 0, "sign": 1}
📝 Ex 0A.27c : réponse enregistrée (int).
WB_ANSWER {"hash": "a189fa0593f1396661079ba96319eb95a4e91b8beec5302150c768ac42cc2179", "id": "0A.27d", "kind": "int", "magnitude": 3, "sign": 1}
📝 Ex 0A.27d : réponse enregistrée (int).
WB_ANSWER {"decimals": 1, "hash": "99df579fbe4c227f5384ca8a9af026d0236a624c00bd27e2aa209af83baa27ab", "hash_coarse": "bbf0d1c7194b414f435b3f2c7b2f1797121047cc5a492e9c6e9c27c6b48e39a1", "id": "0A.27e", "kind": "float", "magnitude": -1, "sign": 1}
📝 Ex 0A.27e : réponse enregistrée (float, 1 décimale(s)).

### Ex 0A.28 — Indexation, tranches et masques booléens 📦 ★ ⏱️ 15 min
**Objectif :** extraire des lignes, des colonnes et des sous-ensembles d'un array avec des indices et des masques.  
**Prérequis :** Ex 0A.27 · fiche §100.8.2 · **Fil rouge :** Penguins · **Parcours :** R, M, C

Les colonnes de `X` sont, dans l'ordre : bec (mm), profondeur du bec (mm), nageoire (mm), masse (g).

a) La longueur de nageoire du 11ᵉ manchot (indice 10).
b) La masse moyenne des manchots d'indices 100 à 199 inclus (wb.check arrondit à 2 décimales).
c) Le nombre de manchots dont le bec dépasse 45 mm **et** la nageoire mesure moins de 200 mm.
d) La proportion de manchots d'**au moins** 4500 g (4500 inclus, comme « heavy » en 0A.20 ; moyenne d'un masque ; wb.check arrondit à 3 décimales).

In [53]:
flipper_10 = X[10, 2]
mean_mass_100s = X[100:200, 3].mean()          # 100 to 199 inclusive: the stop 200 is excluded
n_long_bill = ((X[:, 0] > 45) & (X[:, 2] < 200)).sum()
share_heavy = (X[:, 3] >= 4500).mean()
print(flipper_10, mean_mass_100s, n_long_bill, share_heavy)

185.0 4406.75 46 0.34534534534534533

In [54]:
wb.record("0A.28a", flipper_10, decimals=1)
wb.record("0A.28b", mean_mass_100s, decimals=2, mistakes={"199 est inclus : la tranche s'arrête à 200 (exclu)": X[100:199, 3].mean()})
wb.record("0A.28c", n_long_bill)
wb.record("0A.28d", share_heavy, decimals=3, mistakes={
    "c'est une proportion (entre 0 et 1), pas un nombre de manchots": float((X[:, 3] >= 4500).sum()),
    "« au moins 4500 g » inclut 4500 : >= et non >": (X[:, 3] > 4500).mean()})

WB_ANSWER {"decimals": 1, "hash": "92b426cbd0f37377a452fc2a997ac1778805b52b48863759e3fcd2713fdbf00b", "hash_coarse": "992e08ce59c7bc289b3b21f2fb7b3e09b874b4d120fd2ecbb50c5f6f7b4e966a", "id": "0A.28a", "kind": "float", "magnitude": 2, "sign": 1}
📝 Ex 0A.28a : réponse enregistrée (float, 1 décimale(s)).
WB_ANSWER {"decimals": 2, "hash": "0bfde0f49a7391e90b50977b42204201ec41e7c1d94bffdf679414a9b6049a88", "hash_coarse": "76fc38a707629eedf188fc2a275ef6f24b9de60e437025b588db5a7707c91d29", "id": "0A.28b", "kind": "float", "magnitude": 3, "mistakes": {"55ec0af7fe58d8d98c3eb5818a6ffa7816a0ef3626f13bedb849c64213f7916b": "199 est inclus : la tranche s'arrête à 200 (exclu)"}, "sign": 1}
📝 Ex 0A.28b : réponse enregistrée (float, 2 décimale(s)).
WB_ANSWER {"hash": "cb79cadba9ef7f191e0083fbac86c4f4322bb48184b44deee13253d0a2fff108", "id": "0A.28c", "kind": "int", "magnitude": 1, "sign": 1}
📝 Ex 0A.28c : réponse enregistrée (int).
WB_ANSWER {"decimals": 3, "hash": "98f9b35dfc0581a4e4e9be8d5f2348b95d75b1d48c793f2a37714a7fe7db170c", "hash_coarse": "66ac0c033e9b0c9bc6dbb005cd7997b4df862c23b4063184e92979440f97f416", "id": "0A.28d", "kind": "float", "magnitude": -1, "mistakes": {"286905babd84ebc09315f24065c2c57a5b8fb39317bc4c20a580233b0c2b3837": "« au moins 4500 g » inclut 4500 : >= et non >", "af1d12f8fd1ae46a8f62cbb195c272eb37d4e3f60ee0990229c77e774655dd47": "c'est une proportion (entre 0 et 1), pas un nombre de manchots"}, "sign": 1}
📝 Ex 0A.28d : réponse enregistrée (float, 3 décimale(s)).

### Ex 0A.29 — Vue ou copie : qui est modifié ? 🔮 ★ ⏱️ 10 min
**Objectif :** prévoir quand modifier un morceau d'array modifie l'array d'origine.  
**Prérequis :** Ex 0A.28 · fiche §100.8.2 · **Parcours :** C

```python
a = np.arange(6)
b = a[2:5]
b[0] = 100
c = a[[0, 1]]
c[0] = -1
```

Sans exécuter : a) que vaut `a[2]` à la fin ? b) que vaut `a[0]` ? c) que vaut `a.sum()` ?

Écris ton hypothèse, réponds, puis exécute la cellule « Expérience » pour vérifier.

In [55]:
a = np.arange(6)
b = a[2:5]       # a slice: a VIEW on a
b[0] = 100       # changes a[2]
c = a[[0, 1]]    # a list of indices: a COPY
c[0] = -1        # does not change a
prediction_0A_29a, prediction_0A_29b, prediction_0A_29c = a[2], a[0], a.sum()
print(a, a.sum())

[  0   1 100   3   4   5] 113

In [56]:
wb.record("0A.29a", prediction_0A_29a, mistakes={"une tranche est une VUE : la modifier modifie a": 2})
wb.record("0A.29b", prediction_0A_29b, mistakes={"une liste d'indices crée une COPIE : a n'est pas modifié": -1})
wb.record("0A.29c", prediction_0A_29c)

WB_ANSWER {"hash": "15a4f6bea5fc6aeba48e88a7f19b7047bded28a3dd76f714ba4126d77f1f74be", "id": "0A.29a", "kind": "int", "magnitude": 2, "mistakes": {"42bb1c6628e211f4219c46e9581fcbf904ba56aac373d7634107a9e32a71c024": "une tranche est une VUE : la modifier modifie a"}, "sign": 1}
📝 Ex 0A.29a : réponse enregistrée (int).
WB_ANSWER {"hash": "f87b00dbdc3ef5dbbfb000ae7cc7c26fc68a7a5eb48c27080b92c85f9b140be2", "id": "0A.29b", "kind": "int", "magnitude": null, "mistakes": {"0c7d578d0821936e95aa78bce4d096f71e0e10a05cf83c4965da22dd8e976b1b": "une liste d'indices crée une COPIE : a n'est pas modifié"}, "sign": 0}
📝 Ex 0A.29b : réponse enregistrée (int).
WB_ANSWER {"hash": "c78e2d201dde2deba1e6cc23da19155140242981331e8197cad6762807296557", "id": "0A.29c", "kind": "int", "magnitude": 2, "sign": 1}
📝 Ex 0A.29c : réponse enregistrée (int).

**Expérience** : exécute la cellule et compare avec tes prédictions.

In [57]:
a = np.arange(6)
b = a[2:5]
b[0] = 100
c = a[[0, 1]]
c[0] = -1
print("a =", a, "| a.sum() =", a.sum(), "| shares memory with b:", np.shares_memory(a, b))

a = [  0   1 100   3   4   5] | a.sum() = 113 | shares memory with b: True

### Ex 0A.30 — Calcul vectorisé : unités, normalisation, fonctions universelles 📦 ★ ⏱️ 15 min
**Objectif :** transformer des colonnes entières d'un coup, sans boucle.  
**Prérequis :** Ex 0A.28 · fiche §100.8.3 · **Fil rouge :** Penguins · **Parcours :** R, M, C

Sans aucune boucle :

a) La masse moyenne des manchots de `X`, en **kg** (wb.check arrondit à 3 décimales).
b) La **normalisation min-max** des nageoires, $(f - f_{min}) / (f_{max} - f_{min})$, qui ramène les valeurs entre 0 et 1 : la valeur du premier manchot (3 décimales).
c) Le rapport longueur / profondeur du bec de chaque manchot : sa valeur maximale (2 décimales).
d) Avec `np.where`, l'étiquette `"heavy"` (au moins 4500 g, comme en 0A.20) ou `"not heavy"` de chaque manchot : combien de `"heavy"` ?

In [58]:
mean_kg = (X[:, 3] / 1000).mean()
f = X[:, 2]
flipper_scaled = (f - f.min()) / (f.max() - f.min())
bill_ratio = X[:, 0] / X[:, 1]
labels = np.where(X[:, 3] >= 4500, "heavy", "not heavy")
first_scaled, max_ratio, n_heavy = flipper_scaled[0], bill_ratio.max(), (labels == "heavy").sum()
print(round(mean_kg, 3), flipper_scaled[:3].round(3), max_ratio.round(2), n_heavy)

4.207 [0.153 0.237 0.39 ] 3.61 115

In [59]:
wb.record("0A.30a", mean_kg, decimals=3, mistakes={"utilise la colonne des masses de X (333 manchots complets), pas mass_known": sum(mass_known) / len(mass_known) / 1000})
wb.record("0A.30b", first_scaled, decimals=3)
wb.record("0A.30c", max_ratio, decimals=2)
wb.record("0A.30d", n_heavy, mistakes={"« heavy » commence à 4500 g inclus : >= et non >": int((X[:, 3] > 4500).sum())})

WB_ANSWER {"decimals": 3, "hash": "41a576e7e6fd3f6ec7e85e27260f3d42b3c88e33308e59755473ed814f36796a", "hash_coarse": "547b05ae9588a46d682c897bb06170ef7e5a13485aaf0be06d706c8465f30319", "id": "0A.30a", "kind": "float", "magnitude": 0, "mistakes": {"e87ee0f618ca43416edad7532154478a53893abd3ed415891ad2b75f1154aa82": "utilise la colonne des masses de X (333 manchots complets), pas mass_known"}, "sign": 1}
📝 Ex 0A.30a : réponse enregistrée (float, 3 décimale(s)).
WB_ANSWER {"decimals": 3, "hash": "a16daeeb9f743c254558a5a39b18a442b576c7323164ea0c3e911b1f692e8bf4", "hash_coarse": "e796f566ebe6b28973e715988c8b946f3c9e34784698cc316a23bca884c4e37a", "id": "0A.30b", "kind": "float", "magnitude": -1, "sign": 1}
📝 Ex 0A.30b : réponse enregistrée (float, 3 décimale(s)).
WB_ANSWER {"decimals": 2, "hash": "196ae72c497c3331c63782e33053f73a68d1384ff61eba489eccbf0a3ce833a2", "hash_coarse": "4b70ef8a7e28b2c561db8f3649988036ef4bfe3da2a1df947e681a1a4fc237ac", "id": "0A.30c", "kind": "float", "magnitude": 0, "sign": 1}
📝 Ex 0A.30c : réponse enregistrée (float, 2 décimale(s)).
WB_ANSWER {"hash": "cee5b0a983d2e35d9f40039b4dfdbd6d6579d8bfa7f3fa5f749a3081fd25c13c", "id": "0A.30d", "kind": "int", "magnitude": 2, "mistakes": {"691c999a0d6d386b9e6b5f14af6936ed1d1dcaf48eaa426bad5331a789421beb": "« heavy » commence à 4500 g inclus : >= et non >"}, "sign": 1}
📝 Ex 0A.30d : réponse enregistrée (int).

### Ex 0A.31 — Aléatoire reproductible : `default_rng`, graine, `permutation`, `choice` 📦 ★ ⏱️ 15 min
**Objectif :** tirer au hasard de façon reproductible avec un générateur NumPy.  
**Prérequis :** Ex 0A.27 · fiche §100.8.7 · **Fil rouge :** synth · **Parcours :** R, C

a) Avec `rng = np.random.default_rng(2026)`, simule 10 000 lancers de dé (`rng.integers(1, 7, size=10_000)`) : la **proportion** de 6 (3 décimales). Est-elle proche de ce que tu attendais ?
b) `np.random.default_rng(0).permutation(5)`.
c) Trois indices de manchots tirés **sans remise** parmi 333 : `np.random.default_rng(1).choice(333, size=3, replace=False)`.
d) Deux générateurs créés avec la graine 7 donnent-ils le même premier nombre (`.random()`) ? (`True` ou `False`)
e) Tire 50 manchots sans remise avec `np.random.default_rng(42).choice(len(X), size=50, replace=False)` (des indices de lignes de `X`), puis calcule la moyenne de leurs nageoires (1 décimale).

In [60]:
rng = np.random.default_rng(2026)
rolls = rng.integers(1, 7, size=10_000)       # 7 is excluded: faces 1 to 6
share_six = (rolls == 6).mean()               # close to 1/6 = 0.167
perm = np.random.default_rng(0).permutation(5)
picked = np.random.default_rng(1).choice(333, size=3, replace=False)
same_first = np.random.default_rng(7).random() == np.random.default_rng(7).random()
idx = np.random.default_rng(42).choice(len(X), size=50, replace=False)
sample_mean = X[idx, 2].mean()
print(share_six, perm, picked, same_first, round(sample_mean, 1))

0.1696 [2 4 3 0 1] [169 156 251] True 202.8

In [61]:
wb.record("0A.31a", share_six, decimals=3)
wb.record("0A.31b", perm)
wb.record("0A.31c", picked)
wb.record("0A.31d", same_first)
wb.record("0A.31e", sample_mean, decimals=1, mistakes={
    "permutation(...)[:50] est aussi un tirage sans remise, mais il n'utilise pas le hasard comme choice : utilise choice, comme demandé":
    X[np.random.default_rng(42).permutation(len(X))[:50], 2].mean()})

WB_ANSWER {"decimals": 3, "hash": "f262e9f88d6d2399d124c504e88cf767fdb68012075aa6c62fd1c9d6906ca7b7", "hash_coarse": "add0d1b0fba5e950070d780d845fb32bdaea4e82fe7f8dd9f28476f6d365e272", "id": "0A.31a", "kind": "float", "magnitude": -1, "sign": 1}
📝 Ex 0A.31a : réponse enregistrée (float, 3 décimale(s)).
WB_ANSWER {"decimals": 0, "element_hashes": ["cf0282158ba646216e76f33cc39a466d13337492a6d2957d6c9400d94adf2994", "ac4125c2a85724fa23c51868ce0b81f21aa0f88654be5edac7a0010f7f29220b", "d27200c25764a805eaa572145fccd8d977e0da0f9d1e5b938550d42d3cb8dd1f", "5904123231a5f979f5729f02f4bd180891e10097420a493480861a740a281de9", "0af41a6487fd241e0d749b8e6093e44cac19937ea9540d81a44d18ffe33b5d79"], "hash": "9f9c48b9cb67ec118ce5c886e6cf654b4fc933a1e32f708e7e5ce42bfdca4630", "id": "0A.31b", "integer": true, "kind": "array", "shape": [5]}
📝 Ex 0A.31b : réponse enregistrée (array, 0 décimale(s)).
WB_ANSWER {"decimals": 0, "element_hashes": ["10da779f44b2acc5b3f984ec08bea40126aac031fa3cd2509d438adece0c0ffd", "67dd05cdaf4aee6b305713ac7ba2dfc6b19c5dd42dde05298eeace18b3230ef9", "e9b220ff9edbe482abdb3b830592d317a9afed400ff85054f29cf25f88ba8eab"], "hash": "b42aec51fcfda72431c13ee96098aa0abd1a92fa77925919427753bf2b53b034", "id": "0A.31c", "integer": true, "kind": "array", "shape": [3]}
📝 Ex 0A.31c : réponse enregistrée (array, 0 décimale(s)).
WB_ANSWER {"hash": "7d365511c79fadbf8e77b5256e84b9f9a5056bb808b887782f28af08699a39ca", "id": "0A.31d", "kind": "bool"}
📝 Ex 0A.31d : réponse enregistrée (bool).
WB_ANSWER {"decimals": 1, "hash": "38ac063b47272d336ae1c7a7e4e1b974c2d612110f70e4644f4cac398d5d030b", "hash_coarse": "9c8e3a31d55d3e8963f56ac0d2fe9d4937072b6ccb8c121315179dcecae6585d", "id": "0A.31e", "kind": "float", "magnitude": 2, "mistakes": {"aad256025c91a4f516e3c75cfd7661f107f958b4b872951beab4b20950f1d631": "permutation(...)[:50] est aussi un tirage sans remise, mais il n'utilise pas le hasard comme choice : utilise choice, comme demandé"}, "sign": 1}
📝 Ex 0A.31e : réponse enregistrée (float, 1 décimale(s)).

💡 La proportion de 6 est proche de 1/6 ≈ 0,167 sans être exactement égale : c'est la fluctuation d'échantillonnage (ch. 2).

## Partie E · Premiers pas pandas et matplotlib

Fiche §100.9 et §100.10.1. On lit maintenant le fichier avec pandas, comme on le fera dans tout le workbook.

In [62]:
import matplotlib.pyplot as plt

numeric_cols = ["bill_length_mm", "bill_depth_mm", "flipper_length_mm", "body_mass_g"]
penguins = wb.datasets.load_penguins()   # the same table as data/penguins.csv, used from 0A.33 on

### Ex 0A.32 — Premier contact avec Penguins : `read_csv`, `head`, `info`, `describe` 📦 ★ ⏱️ 13 min
**Objectif :** lire un fichier CSV et en faire le premier état des lieux.  
**Prérequis :** Ex 0A.24 · fiche §100.9.1 · **Fil rouge :** Penguins · **Parcours :** R, M, C

Lis `data/penguins.csv` avec `pd.read_csv` (le chemin `wb.datasets.data_dir() / "penguins.csv"` marche partout), regarde `df.head()`, `df.info()` et `df.describe()`, puis donne :

a) la forme du DataFrame · b) le nombre de valeurs **non manquantes** de la colonne `sex` (lis-le dans `info`) · c) la masse moyenne (wb.check arrondit à l'unité) · d) la plus grande longueur de nageoire · e) le nombre de colonnes numériques résumées par `describe`.

In [63]:
df = pd.read_csv(wb.datasets.data_dir() / "penguins.csv")
df.info()
summary = df.describe()
df_shape = df.shape
sex_non_null = df["sex"].count()        # count() ignores missing values
mean_mass = summary.loc["mean", "body_mass_g"]
max_flipper = summary.loc["max", "flipper_length_mm"]
n_numeric = summary.shape[1]
summary.round(1)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 344 entries, 0 to 343
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   species            344 non-null    object
 1   island             344 non-null    object
 2   bill_length_mm     342 non-null    float64
 3   bill_depth_mm      342 non-null    float64
 4   flipper_length_mm  342 non-null    float64
 5   body_mass_g        342 non-null    float64
 6   sex                333 non-null    object
 7   year               344 non-null    int64
dtypes: float64(4), int64(1), object(3)
memory usage: 21.6+ KB

       bill_length_mm  bill_depth_mm  flipper_length_mm  body_mass_g    year
count           342.0          342.0              342.0        342.0   344.0
mean             43.9           17.2              200.9       4201.8  2008.0
std               5.5            2.0               14.1        802.0     0.8
min              32.1           13.1              172.0       2700.0  2007.0
25%              39.2           15.6              190.0       3550.0  2007.0
50%              44.4           17.3              197.0       4050.0  2008.0
75%              48.5           18.7              213.0       4750.0  2009.0
max              59.6           21.5              231.0       6300.0  2009.0

In [64]:
wb.record("0A.32a", df_shape)
wb.record("0A.32b", sex_non_null, mistakes={"compte les valeurs NON manquantes, pas toutes les lignes": 344})
wb.record("0A.32c", mean_mass, decimals=0)
wb.record("0A.32d", max_flipper, decimals=0)
wb.record("0A.32e", n_numeric, mistakes={"year est aussi une colonne numérique": 4})

WB_ANSWER {"decimals": 0, "element_hashes": ["4cc5fdb7e003b2af511deff60488ee863da4b07287b6b66579b1be3edf46460f", "2a4e12005720128030ffbbfab25df393ca8000d0d96383984760eee424402c43"], "hash": "f1667c95c85094822a47d4ea66a11f48517ee489a3d4ace9eefd7bc706af573c", "id": "0A.32a", "integer": true, "kind": "array", "shape": [2]}
📝 Ex 0A.32a : réponse enregistrée (array, 0 décimale(s)).
WB_ANSWER {"hash": "a6166c645d20529d5f35d2d30c6770ea854a763a695d311fa2c1ab27a1890dcd", "id": "0A.32b", "kind": "int", "magnitude": 2, "mistakes": {"75eef0bbd9a9b2754a2f4c12434ef062ba8e81a195679e6c44a5c184dd99c9b3": "compte les valeurs NON manquantes, pas toutes les lignes"}, "sign": 1}
📝 Ex 0A.32b : réponse enregistrée (int).
WB_ANSWER {"decimals": 0, "hash": "226e86d4409c6fc079211df49a872c4c341d68e8f422df542828f8906b1e5ef4", "id": "0A.32c", "kind": "float", "magnitude": 3, "sign": 1}
📝 Ex 0A.32c : réponse enregistrée (float, 0 décimale(s)).
WB_ANSWER {"decimals": 0, "hash": "21bae2a1b472fef662f11f25253825ec1b2f6c310e9b478dec7f984ab403e309", "id": "0A.32d", "kind": "float", "magnitude": 2, "sign": 1}
📝 Ex 0A.32d : réponse enregistrée (float, 0 décimale(s)).
WB_ANSWER {"hash": "bcf78c55b60695d5de20cd30838a0c2d5027ef51c3e9b9066049f7b0d3024e99", "id": "0A.32e", "kind": "int", "magnitude": 0, "mistakes": {"134d070a13953126ad4feb16a5cd8b8e58e3704c674776e4b32b1b9ae349e989": "year est aussi une colonne numérique"}, "sign": 1}
📝 Ex 0A.32e : réponse enregistrée (int).

### Ex 0A.33 — Sélectionner : colonnes, `loc`, `iloc` et filtres 📦 ★ ⏱️ 15 min
**Objectif :** sélectionner des lignes et des colonnes par étiquette, par position et par condition.  
**Prérequis :** Ex 0A.32, Ex 0A.4 · fiche §100.9.2 · **Fil rouge :** Penguins · **Parcours :** R, M, C

Travaille sur `penguins` (le même tableau que ton `df`).

a) L'île du manchot d'index 100 (`loc`).
b) L'espèce du **dernier** manchot (`iloc`).
c) Le nombre de Gentoo de plus de 5500 g.
d) La longueur moyenne du bec des manchots de l'île Dream (2 décimales).
e) La masse moyenne des Adelie femelles (1 décimale).

In [65]:
island_100 = penguins.loc[100, "island"]
last_species = penguins.iloc[-1]["species"]
n_big_gentoo = len(penguins[(penguins["species"] == "Gentoo") & (penguins["body_mass_g"] > 5500)])
dream_bill = penguins.loc[penguins["island"] == "Dream", "bill_length_mm"].mean()
adelie_female_mass = penguins.loc[(penguins["species"] == "Adelie") & (penguins["sex"] == "female"), "body_mass_g"].mean()
print(island_100, last_species, n_big_gentoo, round(dream_bill, 2), round(adelie_female_mass, 1))

Biscoe Chinstrap 28 44.17 3368.8

In [66]:
wb.record("0A.33a", island_100)
wb.record("0A.33b", last_species)
wb.record("0A.33c", n_big_gentoo)
wb.record("0A.33d", dream_bill, decimals=2)
wb.record("0A.33e", adelie_female_mass, decimals=1)

WB_ANSWER {"hash": "7e4bda925015ae3003095f876a0ef492d0ffc821881ef97768fd9a509c27ba3c", "id": "0A.33a", "kind": "str"}
📝 Ex 0A.33a : réponse enregistrée (str).
WB_ANSWER {"hash": "dde34f985a44efb84b423ab4f15bcf074b2f0ed9cca37842155cce8867d9842c", "id": "0A.33b", "kind": "str"}
📝 Ex 0A.33b : réponse enregistrée (str).
WB_ANSWER {"hash": "143d996f66d0a4dccbf59a17dffe17e80c4ea06ab17730e66da5b9a4a7159de4", "id": "0A.33c", "kind": "int", "magnitude": 1, "sign": 1}
📝 Ex 0A.33c : réponse enregistrée (int).
WB_ANSWER {"decimals": 2, "hash": "cad6f8b63542c3db1b7d607b055cb23dbf720996ecd52e209116903f774c871a", "hash_coarse": "4c001c05dcb9f802fe38b29d86d3151ede05a1314a93f136c5e7628e3473063d", "id": "0A.33d", "kind": "float", "magnitude": 1, "sign": 1}
📝 Ex 0A.33d : réponse enregistrée (float, 2 décimale(s)).
WB_ANSWER {"decimals": 1, "hash": "177ea2bd6f9b19b478cd59ceaed9836dd01df5040ed7874ad082bf0ace6dc0e0", "hash_coarse": "134f01d196790b263d041bfaef330d889d4cb2918d9e4a7e3ae13076f506516c", "id": "0A.33e", "kind": "float", "magnitude": 3, "sign": 1}
📝 Ex 0A.33e : réponse enregistrée (float, 1 décimale(s)).

### Ex 0A.34 — Valeurs manquantes et doublons : `isna`, `dropna`, `fillna`, `duplicated` 📦 ★ ⏱️ 15 min
**Objectif :** repérer, compter et traiter les valeurs manquantes et les lignes en double.  
**Prérequis :** Ex 0A.33 · fiche §100.9.3 · **Fil rouge :** Penguins · **Parcours :** R, M, C

a) Le nombre **total** de valeurs manquantes dans `penguins`.
b) Le nombre de lignes après `dropna()`.
c) Le nombre de lignes après `dropna(subset=["body_mass_g"])`.
d) Après avoir remplacé les sexes manquants par `"unknown"` (`fillna`), combien de `"unknown"` ?
e) `doubled` contient `penguins` plus 5 lignes recopiées : combien de lignes signale `duplicated()` ?
f) La moyenne des nageoires après avoir remplacé leurs valeurs manquantes par la **médiane** (2 décimales).

In [67]:
doubled = pd.concat([penguins, penguins.sample(5, random_state=0)], ignore_index=True)

In [68]:
n_missing = penguins.isna().sum().sum()           # per column, then in total
rows_dropna = len(penguins.dropna())
rows_mass_known = len(penguins.dropna(subset=["body_mass_g"]))
n_unknown = (penguins["sex"].fillna("unknown") == "unknown").sum()
n_duplicates = doubled.duplicated().sum()
flipper = penguins["flipper_length_mm"]
filled_mean = flipper.fillna(flipper.median()).mean()
print(n_missing, rows_dropna, rows_mass_known, n_unknown, n_duplicates, round(filled_mean, 2))

19 333 342 11 5 200.89

In [69]:
wb.record("0A.34a", n_missing, mistakes={"additionne sur TOUTES les colonnes : penguins.isna().sum().sum()": 11})
wb.record("0A.34b", rows_dropna)
wb.record("0A.34c", rows_mass_known)
wb.record("0A.34d", n_unknown)
wb.record("0A.34e", n_duplicates)
wb.record("0A.34f", filled_mean, decimals=2)

WB_ANSWER {"hash": "49f03668fc86d4b01477c9b7e2d36f82373180378ba730784b0a257d6db7f956", "id": "0A.34a", "kind": "int", "magnitude": 1, "mistakes": {"e4b83b77868ae7b6ebfe908876f044678d1299449993fe7760932818751fc7a0": "additionne sur TOUTES les colonnes : penguins.isna().sum().sum()"}, "sign": 1}
📝 Ex 0A.34a : réponse enregistrée (int).
WB_ANSWER {"hash": "b6fc98e7565f2450375d648eb3d4230c3cc9e38204c5ae566a02594b48d6b562", "id": "0A.34b", "kind": "int", "magnitude": 2, "sign": 1}
📝 Ex 0A.34b : réponse enregistrée (int).
WB_ANSWER {"hash": "9486e340e63b781014474e2635c0babc5a6cc80af5d64c8b2e8d0e12b6378566", "id": "0A.34c", "kind": "int", "magnitude": 2, "sign": 1}
📝 Ex 0A.34c : réponse enregistrée (int).
WB_ANSWER {"hash": "f7950ece2bcdca5dbf1135578ee25c200eed07c0f3b92014160e5c3091c535f9", "id": "0A.34d", "kind": "int", "magnitude": 1, "sign": 1}
📝 Ex 0A.34d : réponse enregistrée (int).
WB_ANSWER {"hash": "cde0676aa9f3f43041a9024e5c187b82eb43a0d99c708d3afd1d0f546ac23578", "id": "0A.34e", "kind": "int", "magnitude": 0, "sign": 1}
📝 Ex 0A.34e : réponse enregistrée (int).
WB_ANSWER {"decimals": 2, "hash": "f14044f5c8c91cf02e884f191e5e9f658a011e619a9c4b76654494ab94b02f3c", "hash_coarse": "e00f4ed5b232f3749696f81e2cda8d77afb2cfd0f7cdfd79253aca5e8c5d2ba3", "id": "0A.34f", "kind": "float", "magnitude": 2, "sign": 1}
📝 Ex 0A.34f : réponse enregistrée (float, 2 décimale(s)).

### Ex 0A.35 — De pandas à NumPy : construire `X` et `y` 📦 ★ ⏱️ 13 min
**Objectif :** préparer les features `X` et les labels `y` au format attendu par les modèles.  
**Prérequis :** Ex 0A.34, Ex 0A.27 · fiche §100.9.5 · **Fil rouge :** Penguins · **Parcours :** R, M, C

À partir des manchots **sans valeur manquante** :
- `X` : les 4 colonnes de `numeric_cols`, en array NumPy ;
- `y` : l'espèce, en array NumPy.

a) La forme de `X` · b) la forme de `y` · c) le nombre de valeurs distinctes de `y` (`np.unique`) · d) la moyenne de la colonne des nageoires de `X` (1 décimale).

In [70]:
clean = penguins.dropna()
X = clean[numeric_cols].to_numpy()
y = clean["species"].to_numpy()
print(X.shape, y.shape, np.unique(y), X[:, 2].mean().round(1))

(333, 4) (333,) ['Adelie' 'Chinstrap' 'Gentoo'] 201.0

In [71]:
only_numeric = penguins.dropna(subset=numeric_cols)   # a frequent mistake: keeps the rows where only sex is missing
wb.record("0A.35a", X.shape, mistakes={"enlève TOUTES les lignes incomplètes, même celles où seul sex manque : dropna() sans subset": only_numeric[numeric_cols].shape})
wb.record("0A.35b", y.shape, mistakes={"y est un vecteur : une seule dimension": (333, 1),
                                       "enlève TOUTES les lignes incomplètes, même celles où seul sex manque : dropna() sans subset": (len(only_numeric),)})
wb.record("0A.35c", len(np.unique(y)))
wb.record("0A.35d", X[:, 2].mean(), decimals=1, mistakes={"enlève TOUTES les lignes incomplètes, même celles où seul sex manque : dropna() sans subset": only_numeric["flipper_length_mm"].mean()})

WB_ANSWER {"decimals": 0, "element_hashes": ["f285567578c94f9e653221e353746caf55afa0ae6bce9827b205446a66e8ebc3", "f234d87c4f6e158e2fe4f3d24780e6fc568a1bcdf81c48e79cddf44811eeaf9f"], "hash": "0a75afe1497b869c00d2586078762bc9f31141ae37f6ed52448f6de4585c36fb", "id": "0A.35a", "integer": true, "kind": "array", "mistakes": {"dec714179565478e47d3a44b52f8e9e06ce517b58048e71c2b37cd2fe696aa14": "enlève TOUTES les lignes incomplètes, même celles où seul sex manque : dropna() sans subset"}, "shape": [2]}
📝 Ex 0A.35a : réponse enregistrée (array, 0 décimale(s)).
WB_ANSWER {"decimals": 0, "hash": "b8739c6e79b872b585a6cc5dc4a8d0932eb745785b5fdb52b2717e4aa2ce1598", "id": "0A.35b", "integer": true, "kind": "array", "mistakes": {"10aeb5b4926041f82fa505ec0f52e9ef89ef157d65ece43c942c19d242bf755a": "enlève TOUTES les lignes incomplètes, même celles où seul sex manque : dropna() sans subset", "f473546da2ef9ab06ca3a6b6b5f60413967b19a3748300e25265417e56dab072": "y est un vecteur : une seule dimension"}, "shape": [1]}
📝 Ex 0A.35b : réponse enregistrée (array, 0 décimale(s)).
WB_ANSWER {"hash": "325b0917cb3a8cb2c1ab1ba9caacb51c4fbb4df44367f0d98595b92b1d17c1d5", "id": "0A.35c", "kind": "int", "magnitude": 0, "sign": 1}
📝 Ex 0A.35c : réponse enregistrée (int).
WB_ANSWER {"decimals": 1, "hash": "788991547e8335d638c78624535465fc90d6f16a74f84c4fedea19bdddf49a7a", "hash_coarse": "f5793d1d0bad42dfebbd577840e879014cf7529f182f50ceca2e65b676ef9a90", "id": "0A.35d", "kind": "float", "magnitude": 2, "mistakes": {"a48ee992a1be7b2a09a028ea1975f0570ad27da8a393390d4677f57cee6d14aa": "enlève TOUTES les lignes incomplètes, même celles où seul sex manque : dropna() sans subset"}, "sign": 1}
📝 Ex 0A.35d : réponse enregistrée (float, 1 décimale(s)).

### Ex 0A.36 — Premiers graphiques : `plot`, `scatter`, `hist` 📦 ★ ⏱️ 15 min
**Objectif :** tracer les trois graphiques de base, avec des axes nommés et une légende.  
**Prérequis :** Ex 0A.35 · fiche §100.10.1 · **Fil rouge :** Penguins · **Parcours :** R, C

Trace, avec `fig, ax = plt.subplots()` à chaque fois :

1. l'**histogramme** des masses (25 classes : `bins=25`), axes nommés avec leurs unités ;
2. le **nuage de points** longueur du bec (x) contre profondeur du bec (y), **une couleur par espèce**, avec une légende ;
3. la **courbe** de la masse moyenne par année, une courbe par espèce (le tableau `yearly` est calculé pour toi).

Vérifie ensuite toi-même (réponses dans les solutions) : quelle espèce a le bec le **moins** profond ? La masse moyenne a-t-elle beaucoup changé entre 2007 et 2009 ?

In [72]:
yearly = penguins.groupby(["year", "species"])["body_mass_g"].mean().unstack()
yearly.round(0)

species  Adelie  Chinstrap  Gentoo
year
2007     3696.0     3694.0  5071.0
2008     3742.0     3800.0  5020.0
2009     3665.0     3725.0  5141.0

In [73]:
fig, ax = plt.subplots(figsize=(6, 3.5))
ax.hist(penguins["body_mass_g"].dropna(), bins=25)
ax.set_xlabel("body mass (g)")
ax.set_ylabel("number of penguins")
ax.set_title("Distribution of body mass")
plt.show()

fig, ax = plt.subplots(figsize=(6, 4))
for species, group in penguins.groupby("species"):
    ax.scatter(group["bill_length_mm"], group["bill_depth_mm"], s=14, label=species)
ax.set_xlabel("bill length (mm)")
ax.set_ylabel("bill depth (mm)")
ax.set_title("Bill shape by species")
ax.legend()
plt.show()

fig, ax = plt.subplots(figsize=(6, 3.5))
for species in yearly.columns:
    ax.plot(yearly.index, yearly[species], marker="o", label=species)
ax.set_xticks(yearly.index)
ax.set_xlabel("year")
ax.set_ylabel("mean body mass (g)")
ax.set_title("Mean body mass per year")
ax.legend()
plt.show()

💡 Les Gentoo ont le bec le moins profond (≈ 15 mm, contre ≈ 18,4 mm pour les Adelie et les Chinstrap) ; d'une année à l'autre, la masse moyenne de chaque espèce varie de 120 g au plus, moins de 3 %.

## ✅ Bilan des parties A à E

**Auto-évaluation** (note-toi de 0 à 3 dans `mon_travail/suivi/auto_evaluation.md`) :
1. Sais-tu dire, sans essayer, ce que valent `l[2:5]`, `l[-1]` et `len(l[2:])` ?
2. Sais-tu écrire une fonction qui lève une `ValueError` sur une entrée invalide, et l'appeler dans un `try` ?
3. Sais-tu passer d'un DataFrame pandas à `X` et `y` en NumPy, et donner leurs formes ?

**Pour aller plus loin** : refais 0A.21 et 0A.22 en inversant les rôles (la boucle en compréhension, et inversement) ; puis explore `penguins_raw` (dates, commentaires) : c'est le terrain de jeu des parties F et G.

*Les parties F (Python intermédiaire et avancé), G (NumPy, pandas et matplotlib avancés) et H (outils du pro, mylearn et défi final) seront ajoutées à la prochaine session de génération.*